/** AGROS v4.2.2 - DYNAMIC PREMIER + CHAMPIONSHIP TEST OBSERVATION */
const fs=require('fs');const path=require('path');const ayarlar=require('./ayarlar.js');const league=require('./46_dna_league_engine.js');const dynamicExit=require('./47_dynamic_dna_exit_engine.js');
const VERSION='v4.2.2-DYNAMIC-LEAGUE-TEST';const EXPERIMENT_ID=String(ayarlar.premierTestExperimentId||'DYNAMIC-LEAGUE-EXIT-2026-07-17');const DATA_DIR=path.join(__dirname,'data');const STATE_FILE=path.join(DATA_DIR,'adaptive-league-observation.json');const TRADES_FILE=path.join(DATA_DIR,'adaptive-league-trades.jsonl');
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;const ensure=()=>{if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true})};
function bucket(){return{opened:0,closed:0,tp:0,sl:0,be:0,net:0,grossProfit:0,grossLoss:0,commission:0}}
function blank(){return{version:VERSION,experimentId:EXPERIMENT_ID,startedAt:new Date().toISOString(),opened:0,closed:0,blocked:0,premier:bucket(),championship:bucket(),shadow:bucket(),byDna:{},byExit:{},lastTrades:[],updatedAt:null}}
function archiveOld(){ensure();try{const old=JSON.parse(fs.readFileSync(STATE_FILE,'utf8'));if(old?.experimentId===EXPERIMENT_ID)return;const stamp=new Date().toISOString().replace(/[:.]/g,'-');if(fs.existsSync(STATE_FILE))fs.renameSync(STATE_FILE,path.join(DATA_DIR,`adaptive-league-observation.before-${EXPERIMENT_ID}.${stamp}.json`));if(fs.existsSync(TRADES_FILE))fs.renameSync(TRADES_FILE,path.join(DATA_DIR,`adaptive-league-trades.before-${EXPERIMENT_ID}.${stamp}.jsonl`))}catch(_){}}
function normalize(x){const b=blank();const out=Object.assign(b,x||{});out.premier=Object.assign(bucket(),x?.premier||{});out.championship=Object.assign(bucket(),x?.championship||{});out.shadow=Object.assign(bucket(),x?.shadow||{});out.byDna=x?.byDna||{};out.byExit=x?.byExit||{};out.lastTrades=x?.lastTrades||[];return out}
function read(){archiveOld();try{const x=JSON.parse(fs.readFileSync(STATE_FILE,'utf8'));return x?.experimentId===EXPERIMENT_ID?normalize(x):blank()}catch(_){return blank()}}
function write(x){ensure();const t=STATE_FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(x,null,2));fs.renameSync(t,STATE_FILE)}function append(x){ensure();fs.appendFileSync(TRADES_FILE,JSON.stringify(x)+'\n')}
function signature(pos){return pos?.dnaLeagueProfile?.key||pos?.blackboxAcilis?.strategySignature?.key||''}
function trackFor(lig){if(lig==='PREMIER')return'PREMIER';if(lig==='CHAMPIONSHIP')return'CHAMPIONSHIP';return'SHADOW'}
function bucketFor(st,track){return track==='PREMIER'?st.premier:track==='CHAMPIONSHIP'?st.championship:st.shadow}
function snapshot(pos){if(!pos||ayarlar.premierObservationAktif===false)return null;const key=signature(pos);const player=league.findPlayer(key);const selected=dynamicExit.selectForPosition(pos)||null;const lig=player?.league||'UNRANKED';const track=trackFor(lig);const qualified=track!=='SHADOW';const obs={version:VERSION,key:key||'SIGNATURE_YOK',leagueAtOpen:lig,qualifiedAtOpen:qualified,learningTrack:track,leagueScore:n(player?.leagueScore),expectancy:n(player?.expectancy),profitFactor:n(player?.profitFactor),confidence:n(player?.confidence),regime:selected?.currentRegime||null,exit:selected,openedAt:new Date().toISOString()};pos.premierObservation=obs;const st=read();st.opened++;bucketFor(st,track).opened++;st.byDna[obs.key]=st.byDna[obs.key]||{...bucket(),key:obs.key,lastLeague:obs.leagueAtOpen,lastExit:selected?.selectedAlgorithmId||'ACTUAL'};st.byDna[obs.key].opened++;st.byDna[obs.key].lastLeague=obs.leagueAtOpen;st.byDna[obs.key].lastExit=selected?.selectedAlgorithmId||'ACTUAL';const exitId=selected?.selectedAlgorithmId||'ACTUAL';st.byExit[exitId]=st.byExit[exitId]||{...bucket(),algorithmId:exitId,label:selected?.selectedAlgorithmLabel||'Mevcut Kademe Sistemi'};st.byExit[exitId].opened++;st.updatedAt=obs.openedAt;write(st);return obs}
function apply(b,outcome,net,commission){b.closed++;b.net+=net;b.commission+=commission;if(net>0)b.grossProfit+=net;else if(net<0)b.grossLoss+=Math.abs(net);if(outcome==='TP')b.tp++;else if(outcome==='BE')b.be++;else b.sl++}
function close(pos,result={}){const obs=pos?.premierObservation;if(!obs)return null;const net=n(result.net),commission=n(result.commission),outcome=String(result.outcome||'SL').toUpperCase();const exitId=obs.exit?.selectedAlgorithmId||'ACTUAL';const row={version:VERSION,experimentId:EXPERIMENT_ID,closedAt:new Date().toISOString(),openedAt:obs.openedAt,symbol:pos.sym,direction:pos.yon,key:obs.key,track:obs.learningTrack,leagueAtOpen:obs.leagueAtOpen,leagueScore:obs.leagueScore,confidence:obs.confidence,regime:obs.regime,exitAlgorithmId:exitId,exitAlgorithmLabel:obs.exit?.selectedAlgorithmLabel||'Mevcut Kademe Sistemi',exitScope:obs.exit?.selectionScope||'NONE',outcome,net,commission,reason:result.reason||'',entry:n(pos.girisFiyati),exitPrice:n(result.exitPrice),mfePct:n(pos?.sanalDynamicExit?.mfePct||pos?.exitReplay?.mfePct),capturePct:n(result.capturePct||pos?.sanalDynamicExit?.capturePct)};const st=read();st.closed++;apply(bucketFor(st,obs.learningTrack),outcome,net,commission);st.byDna[obs.key]=st.byDna[obs.key]||{...bucket(),key:obs.key,lastLeague:obs.leagueAtOpen,lastExit:exitId};apply(st.byDna[obs.key],outcome,net,commission);st.byDna[obs.key].lastLeague=obs.leagueAtOpen;st.byDna[obs.key].lastExit=exitId;st.byExit[exitId]=st.byExit[exitId]||{...bucket(),algorithmId:exitId,label:row.exitAlgorithmLabel};apply(st.byExit[exitId],outcome,net,commission);st.lastTrades=[row,...(st.lastTrades||[])].slice(0,100);st.updatedAt=row.closedAt;write(st);append(row);return row}
function metrics(b={}){const d=n(b.tp)+n(b.sl);return{...b,winRate:d?100*n(b.tp)/d:0,profitFactor:n(b.grossLoss)>0?n(b.grossProfit)/n(b.grossLoss):(n(b.grossProfit)>0?999:0),expectancy:n(b.closed)?n(b.net)/n(b.closed):0}}
function blocked(key,reason='TEST_HAVUZU_DISI'){const st=read();st.blocked=n(st.blocked)+1;st.updatedAt=new Date().toISOString();write(st);return{key,reason,experimentId:EXPERIMENT_ID}}
function activeRows(active=[]){return active.map(x=>{const o=x?.premierObservation;if(!o)return null;return{symbol:x.sym,direction:x.yon,key:o.key,track:o.learningTrack,league:o.leagueAtOpen,score:o.leagueScore,exit:o.exit?.selectedAlgorithmLabel||'Mevcut Kademe'}}).filter(Boolean)}
function model(active=[]){const st=read();let leagueModel=null;try{leagueModel=league.build?league.build():null}catch(_){leagueModel=null;}return{...st,premier:metrics(st.premier),championship:metrics(st.championship),shadow:metrics(st.shadow),leagueSizes:leagueModel?.leagueSizes||{},active:activeRows(active),topDna:Object.values(st.byDna||{}).map(metrics).sort((a,b)=>b.net-a.net||b.opened-a.opened),topActiveDna:Object.values(st.byDna||{}).map(metrics).sort((a,b)=>b.opened-a.opened||b.net-a.net),topExit:Object.values(st.byExit||{}).map(metrics).sort((a,b)=>b.net-a.net)}}
function fmt(label,b){return`${label} | Açık ${b.opened-b.closed} | Kapalı ${b.closed} | Başarı %${b.winRate.toFixed(2)} | Net ${b.net.toFixed(4)} | Kom ${b.commission.toFixed(4)} | PF ${b.profitFactor>=999?'∞':b.profitFactor.toFixed(2)} | Exp ${b.expectancy.toFixed(4)}`}

function compactTelegram(active=[]){if(ayarlar.premierObservationTelegramAktif===false)return'';const m=model(active),p=m.premier,c=m.championship;const premierDna=n(m.leagueSizes?.premier),champDna=n(m.leagueSizes?.championship);let t='🧬 <b>DYNAMIC LEAGUE TEST</b>\n';t+=`🏆 Premier DNA ${premierDna} | Açılan ${p.opened} | Aktif ${Math.max(0,p.opened-p.closed)} | Kapalı ${p.closed} | Net ${p.net.toFixed(4)}\n`;t+=`🥈 Championship DNA ${champDna} | Açılan ${c.opened} | Aktif ${Math.max(0,c.opened-c.closed)} | Kapalı ${c.closed} | Net ${c.net.toFixed(4)}\n`;t+=`📊 Yeni test toplamı ${p.opened+c.opened} | Net ${(p.net+c.net).toFixed(4)} | Kom ${(p.commission+c.commission).toFixed(4)}\n`;const top=(m.topActiveDna||[]).filter(x=>x.opened>0).slice(0,5);if(top.length)t+='🎮 <b>En Çok İşlem Açan DNA</b>\n'+top.map((x,i)=>`${i+1}. ${x.key} | ${x.lastLeague} | Açılan ${x.opened} | Kapalı ${x.closed} | Net ${x.net.toFixed(4)}`).join('\n');else t+='🎮 Henüz yeni lig işlemi açılmadı.';return t}

function telegram(active=[]){if(ayarlar.premierObservationTelegramAktif===false)return'';const m=model(active),p=m.premier,c=m.championship,s=m.shadow;let t='\n\n💎 <b>DYNAMIC LEAGUE + EXIT TEST KASASI</b>\n';t+=`🧪 Deney: ${m.experimentId} | Başlangıç: ${m.startedAt}\n`;t+=`🚫 Premier/Championship dışı engellenen giriş: ${n(m.blocked)}\n`;t+=fmt('🏆 Premier',p)+'\n';t+=fmt('🥈 Championship',c)+'\n';t+=`📊 Birleşik test | Açılan ${p.opened+c.opened} | Kapalı ${p.closed+c.closed} | Net ${(p.net+c.net).toFixed(4)} | Kom ${(p.commission+c.commission).toFixed(4)}\n`;const pa=m.active.filter(x=>x.track==='PREMIER'),ca=m.active.filter(x=>x.track==='CHAMPIONSHIP');t+=`📦 Aktif Premier ${pa.length} | Aktif Championship ${ca.length} | Shadow ${m.active.length-pa.length-ca.length}\n`;const act=[...pa,...ca];if(act.length)t+=act.slice(0,Number(ayarlar.premierObservationTelegramTopAktif||8)).map((x,i)=>`${i+1}. ${x.symbol} ${x.direction} | ${x.league} | Skor ${n(x.score).toFixed(1)} | ${x.exit}`).join('\n');if(m.topDna.length){t+='\n🧬 <b>Test Kasası En Kârlı DNA’lar</b>\n'+m.topDna.slice(0,5).map((x,i)=>`${i+1}. ${x.key} | ${x.lastLeague} | N${x.closed} | Net ${x.net.toFixed(4)} | PF ${x.profitFactor>=999?'∞':x.profitFactor.toFixed(2)}`).join('\n')}t+='\n🔄 Lig üyeleri sabit değildir; transferlerde sanal işlem havuzu otomatik güncellenir. Eski 2246 işlem bu yeni kasaya karışmaz.';return t}
module.exports={VERSION,EXPERIMENT_ID,STATE_FILE,TRADES_FILE,read,blocked,snapshot,close,model,compactTelegram,telegram};
