/** AGROS v4.0 - ADAPTIVE LEAGUE OBSERVATION & SHADOW STATISTICS */
const fs=require('fs');const path=require('path');const ayarlar=require('./ayarlar.js');const league=require('./46_dna_league_engine.js');const dynamicExit=require('./47_dynamic_dna_exit_engine.js');
const VERSION='v4.0.0-ADAPTIVE-LEAGUE-OBSERVATION';const DATA_DIR=path.join(__dirname,'data');const STATE_FILE=path.join(DATA_DIR,'adaptive-league-observation.json');const TRADES_FILE=path.join(DATA_DIR,'adaptive-league-trades.jsonl');
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;const ensure=()=>{if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true})};
function blank(){return{version:VERSION,opened:0,closed:0,premier:bucket(),shadow:bucket(),byDna:{},byExit:{},lastTrades:[],updatedAt:null}}function bucket(){return{opened:0,closed:0,tp:0,sl:0,be:0,net:0,grossProfit:0,grossLoss:0,commission:0}}
function read(){try{return Object.assign(blank(),JSON.parse(fs.readFileSync(STATE_FILE,'utf8')))}catch(_){return blank()}}function write(x){ensure();const t=STATE_FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(x,null,2));fs.renameSync(t,STATE_FILE)}function append(x){ensure();fs.appendFileSync(TRADES_FILE,JSON.stringify(x)+'\n')}
function signature(pos){return pos?.dnaLeagueProfile?.key||pos?.blackboxAcilis?.strategySignature?.key||''}
function snapshot(pos){if(!pos||ayarlar.premierObservationAktif===false)return null;const key=signature(pos);const player=league.findPlayer(key);const selected=dynamicExit.selectForPosition(pos)||null;const qualified=player?.league==='PREMIER';const obs={version:VERSION,key:key||'SIGNATURE_YOK',leagueAtOpen:player?.league||'UNRANKED',qualifiedAtOpen:qualified,learningTrack:qualified?'PREMIER':'SHADOW',leagueScore:n(player?.leagueScore),expectancy:n(player?.expectancy),profitFactor:n(player?.profitFactor),confidence:n(player?.confidence),regime:selected?.currentRegime||null,exit:selected,openedAt:new Date().toISOString()};pos.premierObservation=obs;const st=read();st.opened++;const b=qualified?st.premier:st.shadow;b.opened++;st.updatedAt=obs.openedAt;write(st);return obs}
function apply(b,outcome,net,commission){b.closed++;b.net+=net;b.commission+=commission;if(net>0)b.grossProfit+=net;else if(net<0)b.grossLoss+=Math.abs(net);if(outcome==='TP')b.tp++;else if(outcome==='BE')b.be++;else b.sl++}
function close(pos,result={}){const obs=pos?.premierObservation;if(!obs)return null;const net=n(result.net),commission=n(result.commission),outcome=String(result.outcome||'SL').toUpperCase();const exitId=obs.exit?.selectedAlgorithmId||'ACTUAL';const row={version:VERSION,closedAt:new Date().toISOString(),openedAt:obs.openedAt,symbol:pos.sym,direction:pos.yon,key:obs.key,track:obs.learningTrack,leagueAtOpen:obs.leagueAtOpen,leagueScore:obs.leagueScore,confidence:obs.confidence,regime:obs.regime,exitAlgorithmId:exitId,exitAlgorithmLabel:obs.exit?.selectedAlgorithmLabel||'Mevcut Kademe Sistemi',exitScope:obs.exit?.selectionScope||'NONE',outcome,net,commission,reason:result.reason||'',entry:n(pos.girisFiyati),exitPrice:n(result.exitPrice)};const st=read();st.closed++;apply(obs.qualifiedAtOpen?st.premier:st.shadow,outcome,net,commission);st.byDna[obs.key]=st.byDna[obs.key]||{...bucket(),key:obs.key,lastLeague:obs.leagueAtOpen,lastExit:exitId};apply(st.byDna[obs.key],outcome,net,commission);st.byDna[obs.key].lastLeague=obs.leagueAtOpen;st.byDna[obs.key].lastExit=exitId;st.byExit[exitId]=st.byExit[exitId]||{...bucket(),algorithmId:exitId,label:row.exitAlgorithmLabel};apply(st.byExit[exitId],outcome,net,commission);st.lastTrades=[row,...(st.lastTrades||[])].slice(0,100);st.updatedAt=row.closedAt;write(st);append(row);return row}
function metrics(b={}){const d=n(b.tp)+n(b.sl);return{...b,winRate:d?100*n(b.tp)/d:0,profitFactor:n(b.grossLoss)>0?n(b.grossProfit)/n(b.grossLoss):(n(b.grossProfit)>0?999:0),expectancy:n(b.closed)?n(b.net)/n(b.closed):0}}
function activeRows(active=[]){return active.map(x=>{const o=x?.premierObservation;if(!o)return null;return{symbol:x.sym,direction:x.yon,key:o.key,track:o.learningTrack,league:o.leagueAtOpen,score:o.leagueScore,exit:o.exit?.selectedAlgorithmLabel||'Mevcut Kademe'}}).filter(Boolean)}
function model(active=[]){const st=read();return{...st,premier:metrics(st.premier),shadow:metrics(st.shadow),active:activeRows(active),topDna:Object.values(st.byDna||{}).map(metrics).sort((a,b)=>b.net-a.net),topExit:Object.values(st.byExit||{}).map(metrics).sort((a,b)=>b.net-a.net)}}
function telegram(active=[]){if(ayarlar.premierObservationTelegramAktif===false)return'';const m=model(active),p=m.premier,s=m.shadow;let t='\n\n💎 <b>ADAPTIVE LEAGUE GERÇEK BAŞARI</b>\n';t+=`🏆 Premier | Açık ${p.opened-p.closed} | Kapalı ${p.closed} | Başarı %${p.winRate.toFixed(2)} | Net ${p.net.toFixed(4)} | PF ${p.profitFactor>=999?'∞':p.profitFactor.toFixed(2)} | Exp ${p.expectancy.toFixed(4)}\n`;t+=`🧪 Shadow | Açık ${s.opened-s.closed} | Kapalı ${s.closed} | Başarı %${s.winRate.toFixed(2)} | Net ${s.net.toFixed(4)} | PF ${s.profitFactor>=999?'∞':s.profitFactor.toFixed(2)}\n`;const pa=m.active.filter(x=>x.track==='PREMIER');t+=`📦 Aktif Premier ${pa.length} | Aktif Shadow ${m.active.length-pa.length}\n`;if(pa.length)t+=pa.slice(0,8).map((x,i)=>`${i+1}. ${x.symbol} ${x.direction} | Skor ${n(x.score).toFixed(1)} | ${x.exit}`).join('\n');if(m.topDna.length){t+='\n🧬 <b>En Kârlı DNA’lar</b>\n'+m.topDna.slice(0,5).map((x,i)=>`${i+1}. ${x.key} | N${x.closed} | Net ${x.net.toFixed(4)} | PF ${x.profitFactor>=999?'∞':x.profitFactor.toFixed(2)}`).join('\n')}t+='\n🔬 Alt lig işlemleri ana Premier kasasına karışmadan öğrenmeye devam eder.';return t}
module.exports={VERSION,STATE_FILE,TRADES_FILE,read,snapshot,close,model,telegram};
