/** AGROS v4.0 - ADAPTIVE TRADING LEAGUE ORCHESTRATOR */
const fs=require('fs');const path=require('path');const ayarlar=require('./ayarlar.js');const league=require('./46_dna_league_engine.js');const dynamicExit=require('./47_dynamic_dna_exit_engine.js');const observation=require('./48_premier_observation_engine.js');
const VERSION='v4.0.1-ADAPTIVE-TRADING-LEAGUE-RAM-SAFE';const DATA=path.join(__dirname,'data');const STORY=path.join(DATA,'dna-story.json');const DASH=path.join(DATA,'adaptive-trading-league-dashboard.json');const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function readJson(f,d){try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch(_){return d}}function write(f,x){if(!fs.existsSync(DATA))fs.mkdirSync(DATA,{recursive:true});const t=f+'.tmp';fs.writeFileSync(t,JSON.stringify(x,null,2));fs.renameSync(t,f)}
function readJsonl(f,limit=5000){try{return fs.readFileSync(f,'utf8').trim().split(/\r?\n/).filter(Boolean).slice(-limit).map(x=>JSON.parse(x))}catch(_){return[]}}
function emptyExitModel(){return{version:dynamicExit.VERSION,generatedAt:null,currentRegime:{key:'MIXED|VOL_MEDIUM',regime:'MIXED',regimeFamily:'MIXED',volatility:'MEDIUM',window:0,distribution:{}},dna:[]}}
function build(active=[],options={}){const lm=options.leagueModel||league.build({}, {persist:options.persist!==false});const em=dynamicExit.readModel()||emptyExitModel();const om=observation.model(active);const transfers=readJsonl(league.TRANSFER_FILE,10000);const old=readJson(STORY,{version:VERSION,dna:{}});const now=new Date().toISOString();for(const p of lm.allPlayers||[]){const s=old.dna[p.key]||{key:p.key,firstSeenAt:now,timeline:[]};const current=league.findPlayer(p.key,lm);const prev=s.current||{};const exitId=p.exit?.algorithmId||'ACTUAL';if(prev.league!==current?.league||prev.exitId!==exitId||prev.momentum!==p.momentum?.status){s.timeline.unshift({at:now,type:'STATE_CHANGE',from:prev,to:{league:current?.league||'UNRANKED',exitId,momentum:p.momentum?.status,regime:lm.regime?.activeDirection,score:p.leagueScore,expectancy:p.expectancy,profitFactor:p.profitFactor}});s.timeline=s.timeline.slice(0,100)}s.current={league:current?.league||'UNRANKED',exitId,momentum:p.momentum?.status,regime:lm.regime?.activeDirection,score:p.leagueScore,expectancy:p.expectancy,profitFactor:p.profitFactor,total:p.total,updatedAt:now};old.dna[p.key]=s}old.generatedAt=now;old.transferCount=transfers.length;write(STORY,old);
const dashboard={version:VERSION,generatedAt:now,mode:'FINAL_OBSERVATION_BEFORE_REAL_ORDERS',features:{dynamicLeague:true,dynamicExitIntelligence:true,shadowLearning:true,premierAutoSelection:true,realtimePromotion:true,realtimeRelegation:true,dynamicRegimeDetection:true,dynamicExitSelection:true,liveConfidence:true,leagueDashboard:true,telegramLeague:true,shadowStatistics:true,promotionHistory:true,exitHistory:true,dnaStory:true},regime:lm.regime,leagueSizes:lm.leagueSizes,premier:lm.leagues.premier,championship:lm.leagues.championship,transfers:transfers.slice(-50).reverse(),exitRegime:em?.currentRegime||null,observation:{premier:om.premier,shadow:om.shadow,topDna:om.topDna.slice(0,20),topExit:om.topExit.slice(0,20)},files:{story:STORY,league:league.LEAGUE_FILE,transfers:league.TRANSFER_FILE,exitHistory:dynamicExit.HISTORY_JSONL||path.join(DATA,'dynamic-dna-exit-selection-history.jsonl')}};write(DASH,dashboard);return dashboard}
function telegram(active=[]){if(ayarlar.adaptiveTradingLeagueTelegramAktif===false)return'';const m=build(active);let t='\n\n🧠 <b>AGROS v4.0 ADAPTIVE TRADING LEAGUE</b>\n';t+=`🌦️ Rejim: ${m.regime?.activeDirection||'NEUTRAL'} | Exit rejimi: ${m.exitRegime?.key||'BILINMIYOR'}\n`;t+=`🏆 Premier ${m.leagueSizes.premier} | 🥈 Championship ${m.leagueSizes.championship} | 🌱 Gelişim ${m.leagueSizes.development} | 📚 Tarihsel ${m.leagueSizes.historical}\n`;t+=`💎 Premier Net ${n(m.observation.premier.net).toFixed(4)} | PF ${m.observation.premier.profitFactor>=999?'∞':n(m.observation.premier.profitFactor).toFixed(2)} | Exp ${n(m.observation.premier.expectancy).toFixed(4)}\n`;t+=`🧪 Shadow Kapalı ${n(m.observation.shadow.closed)} | Net ${n(m.observation.shadow.net).toFixed(4)}\n`;if(m.premier.length)t+='⭐ <b>Premier Liderleri</b>\n'+m.premier.slice(0,5).map((x,i)=>`${i+1}. ${x.label} | N${x.total} | Exp ${x.expectancy>=0?'+':''}${n(x.expectancy).toFixed(4)} | PF ${n(x.profitFactor).toFixed(2)} | ${x.exit?.algorithmLabel||'ACTUAL'}`).join('\n');if(m.transfers.length)t+='\n🔁 <b>Son Transferler</b>\n'+m.transfers.slice(0,5).map(x=>`${x.from||'YENİ'} → ${x.to} | ${x.key}`).join('\n');t+='\n📖 Terfi/düşüş, exit değişimi ve DNA yaşam öyküsü kalıcı olarak kaydedilir.';return t}
module.exports={VERSION,STORY,DASH,build,telegram};
