/** AGROS v4.5 — kalıcı DNA Kimlik Kartları. */
const fs=require('fs');const path=require('path');const league=require('./46_dna_league_engine.js');const dynamic=require('./47_dynamic_dna_exit_engine.js');const io=require('./53_memory_safe_io.js');
const OUT=path.join(__dirname,'data','dna-identity-cards.json');const VERSION='v4.5.1-DNA-IDENTITY-CARDS-MEMORY-SAFE';
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d;}function leagueName(k,m){for(const [l,a] of Object.entries(m?.leagues||{}))if((a||[]).some(x=>league.normalizeSignatureKey(x.key)===k))return l.toUpperCase();return'UNRANKED';}
function chars(p){return{trend:Boolean(p.regimeAligned||p.momentum?.status==='GUCLENIYOR'),volatility:Boolean(p.volatility||p.regime),profit:n(p.expectancy)>0&&n(p.net)>0,risk:n(p.profitFactor)>1&&p.death!=='OLUM_RISKI'};}
function trend(p){if(p.momentum?.status)return p.momentum.status;const r=p.recent5||{};return n(r.net)>0&&n(r.expectancy)>0?'GUCLENIYOR':n(r.net)<0?'ZAYIFLIYOR':'STABIL';}
function build(lm=null,dm=null){lm=lm||league.build();dm=dm||dynamic.readModel()||{};const old=io.readJsonBounded(OUT,{cards:[]},{maxBytes:24*1024*1024});const oldMap=new Map((old.cards||[]).map(x=>[x.dna,x]));const players=[...Object.values(lm.leagues||{}).flat()];const seen=new Set(),cards=[];for(const p of players){const dna=league.normalizeSignatureKey(p.key);if(!dna||seen.has(dna))continue;seen.add(dna);const d=(dm.dna||[]).find(x=>league.normalizeSignatureKey(x.key)===dna);const ex=d?.allBest||null,prev=oldMap.get(dna);const resultSeq=(p.recent5?.results||p.recent5?.sequence||'');cards.push({dna,league:leagueName(dna,lm),previousLeague:prev?.league||null,premierScore:+n(p.leagueScore).toFixed(2),trades:n(p.total),tp:n(p.tp),sl:n(p.sl),be:n(p.be),winRate:+n(p.winRate).toFixed(2),net:+n(p.net).toFixed(4),profitFactor:+n(p.profitFactor).toFixed(2),expectancy:+n(p.expectancy).toFixed(4),last5:typeof resultSeq==='string'?resultSeq:'',trend:trend(p),eliteExit:ex?.algorithmLabel||p.exit?.algorithmLabel||'Mevcut Kademe',eliteExitId:ex?.algorithmId||p.exit?.algorithmId||'ACTUAL',previousExit:prev?.eliteExit||null,exitAdvantage:+n(ex?.deltaUsdt||ex?.netUsdt).toFixed(4),characters:chars(p),premierAudit:{eligible:n(p.total)>=10&&n(p.expectancy)>0&&n(p.profitFactor)>1&&n(p.net)>0,reasons:[n(p.total)>=10?`N ${n(p.total)} >= 10`:`N ${n(p.total)} < 10`,n(p.expectancy)>0?'Expectancy pozitif':'Expectancy pozitif değil',n(p.profitFactor)>1?'PF > 1':'PF <= 1',n(p.net)>0?'Net pozitif':'Net pozitif değil']},updatedAt:new Date().toISOString()});}const out={version:VERSION,createdAt:new Date().toISOString(),count:cards.length,cards:cards.sort((a,b)=>b.premierScore-a.premierScore)};io.writeJsonAtomic(OUT,out);return out;}
function telegram(out=build(),limit=5){return `\n\n🪪 <b>DNA KİMLİK KARTLARI — v4.5</b>\nToplam profil: ${out.count}\n`+out.cards.slice(0,limit).map((x,i)=>`${i+1}. ${x.dna}\n   ${x.league} | Skor ${x.premierScore} | N${x.trades} | WR %${x.winRate} | Net ${x.net>=0?'+':''}${x.net} | PF ${x.profitFactor}\n   ⭐ ${x.eliteExit} | ${x.trend}`).join('\n');}
module.exports={VERSION,OUT,build,telegram};
