'use strict';
const fs=require('fs'); const path=require('path'); const crypto=require('crypto');
const ayarlar=require('./ayarlar.js'); const io=require('./53_memory_safe_io.js');
const VERSION='v6.3.9-RENKO-PROFIT-TRAIL-OBSERVABILITY';
const DATA_DIR=process.env.AGROS_DATA_DIR?path.resolve(process.env.AGROS_DATA_DIR):path.join(__dirname,'data');
const STATE_FILE=path.join(DATA_DIR,'st2-renko-exit-evolution.json'); const BACKUP_FILE=`${STATE_FILE}.bak`; const LEDGER_FILE=path.join(DATA_DIR,'st2-renko-exit-evolution-ledger.jsonl');
const CANDIDATES=()=> (ayarlar.renkoCikisAdayTugla||[0.5,0.75,1,1.25,1.5,1.75,2]).map(Number).filter(x=>x>0).sort((a,b)=>a-b);
const DEFAULT_TRAIL=()=>Number(ayarlar.renkoCikisVarsayilanTugla||1);
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d;} function key(y,p){return `${String(y||'').toUpperCase()}|${String(p||'UNKNOWN').toUpperCase()}`;}
function blankMetric(){return {samples:0,tp:0,sl:0,be:0,net:0,grossProfit:0,grossLoss:0,mfeCaptureSum:0};}
function blank(){return {version:VERSION,updatedAt:null,profiles:{},processedIds:{},health:{duplicate:0,restartGap:0,manualExcluded:0,saveErrors:0,loadErrors:0}};}
function ensure(){if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});}
function read(){ensure();try{return {...blank(),...JSON.parse(fs.readFileSync(STATE_FILE,'utf8'))};}catch(e){try{return {...blank(),...JSON.parse(fs.readFileSync(BACKUP_FILE,'utf8'))};}catch(_){return blank();}}}
function write(s){ensure();try{if(fs.existsSync(STATE_FILE))fs.copyFileSync(STATE_FILE,BACKUP_FILE);s.version=VERSION;s.updatedAt=new Date().toISOString();io.writeJsonAtomic(STATE_FILE,s);return s;}catch(e){s.health.saveErrors=n(s.health?.saveErrors)+1;throw e;}}
function metric(m){const samples=n(m.samples), loss=n(m.grossLoss);return {...m,wr:samples?100*n(m.tp)/samples:0,pf:loss>0?n(m.grossProfit)/loss:(n(m.grossProfit)>0?999:0),expectancy:samples?n(m.net)/samples:0,mfeCapture:samples?n(m.mfeCaptureSum)/samples:0};}
function choose(p){const rows=Object.entries(p.candidates||{}).map(([x,m])=>({trail:n(x),...metric(m)})).filter(x=>x.samples>=Math.max(3,n(ayarlar.renkoCikisIlkAtamaKapanis,3)));rows.sort((a,b)=>b.net-a.net||b.pf-a.pf||b.expectancy-a.expectancy||a.trail-b.trail);return rows[0]||null;}
function activeFor(yon,pattern){const s=read(),p=s.profiles[key(yon,pattern)];return n(p?.activeTrail,DEFAULT_TRAIL());}
function assign(pos){if(!pos||pos.renkoExitAssignment)return pos?.renkoExitAssignment;const ga=pos.girisAnalizi||{};const trail=activeFor(pos.yon,ga.patternKodu);pos.renkoExitAssignment={patternKey:key(pos.yon,ga.patternKodu),assignedTrailBricks:trail,assignedAt:new Date().toISOString(),activationMode:'AFTER_FIRST_PROFIT_PROTECTION',status:'WAITING_SAFE_START'};return pos.renkoExitAssignment;}
function firstProtectionReady(pos){return pos?.breakevenAktif===true && n(pos?.korunanKarYuzdesi,n(pos?.labBeTamponYuzde,0))>=0;}
function stopSource(pos,old,floor,candidate,mfeFloor,effective){
 const eps=Math.max(1e-12,Math.abs(n(effective))*1e-10);
 const rows=[['MEVCUT_STOP',old],['ILK_KAR_KORUMA',floor],['RENKO_TAKIP',candidate],['MFE_KORUMA',mfeFloor]].filter(([,v])=>Number.isFinite(Number(v))&&Number(v)>0);
 const hit=rows.find(([,v])=>Math.abs(Number(v)-Number(effective))<=eps);
 return hit?.[0]||'BILINMIYOR';
}
function sourceLabel(src){return ({MEVCUT_STOP:'Mevcut stop',ILK_KAR_KORUMA:'İlk kâr koruma',RENKO_TAKIP:'Renko takip stopu',MFE_KORUMA:'MFE kâr koruma',BILINMIYOR:'Bilinmiyor'})[src]||String(src||'Bilinmiyor');}
function peakProfitPct(pos,peak){const entry=n(pos?.girisFiyati);if(!(entry>0)||!(peak>0))return 0;return pos.yon==='LONG'?(peak-entry)/entry*100:(entry-peak)/entry*100;}
function mfeProtectionStop(pos,peak){
 const entry=n(pos?.girisFiyati);if(!(entry>0)||!(peak>0))return null;
 const trigger=Math.max(0,n(ayarlar.renkoCikisMfeKorumaTetikYuzde,0.40));
 const ratio=Math.max(0,Math.min(1,n(ayarlar.renkoCikisMinMfeKorumaOrani,0.60)));
 const peakPct=peakProfitPct(pos,peak);if(peakPct<trigger||ratio<=0)return null;
 const protectedPct=peakPct*ratio;
 return pos.yon==='LONG'?entry*(1+protectedPct/100):entry*(1-protectedPct/100);
}
function update(pos,price){assign(pos);const a=pos.renkoExitAssignment;if(!firstProtectionReady(pos))return {active:false,changed:false};const box=n(pos?.girisAnalizi?.renkoBoxSize||pos?.renkoBoxSize);if(!(box>0))return {active:false,changed:false,reason:'BOX_SIZE_MISSING'};
 if(!pos.renkoExitActivated){pos.renkoExitActivated=true;pos.renkoExitActivatedAt=new Date().toISOString();pos.renkoExitFirstProtectionStop=pos.sl;pos.renkoExitPeak=price;a.status='ACTIVE';}
 pos.renkoExitPeak=pos.yon==='LONG'?Math.max(n(pos.renkoExitPeak,price),price):Math.min(n(pos.renkoExitPeak,price),price);
 const candidate=pos.yon==='LONG'?pos.renkoExitPeak-box*n(a.assignedTrailBricks):pos.renkoExitPeak+box*n(a.assignedTrailBricks);
 const mfeFloor=mfeProtectionStop(pos,pos.renkoExitPeak);
 const floor=n(pos.renkoExitFirstProtectionStop,pos.sl); const old=n(pos.sl);
 if(!(old>0) || !(floor>0) || !(candidate>0) || !Number.isFinite(candidate)) return {active:true,justActivated:!pos.renkoExitTakeoverNotified,changed:false,reason:'INVALID_STOP_INPUT',candidate,old,floor,mfeFloor};
 const effective=pos.yon==='LONG'?Math.max(old,floor,candidate,n(mfeFloor,0)):Math.min(old,floor,candidate,n(mfeFloor,Number.POSITIVE_INFINITY));
 if(!(effective>0) || !Number.isFinite(effective)) return {active:true,justActivated:!pos.renkoExitTakeoverNotified,changed:false,reason:'INVALID_EFFECTIVE_STOP',candidate,effective,mfeFloor};
 const source=stopSource(pos,old,floor,candidate,mfeFloor,effective);
 const changed=pos.yon==='LONG'?effective>old:effective<old;if(changed){pos.sl=effective;pos.renkoExitAppliedTrailBricks=n(a.assignedTrailBricks);pos.renkoExitMfeProtectionStop=mfeFloor;pos.renkoExitLastStopSource=source;pos.renkoExitLastStopSourceLabel=sourceLabel(source);pos.renkoExitLastStopUpdatedAt=new Date().toISOString();}
 return {active:true,justActivated:!pos.renkoExitTakeoverNotified,changed,candidate,effective,mfeFloor,source,sourceLabel:sourceLabel(source),peakProfitPct:peakProfitPct(pos,pos.renkoExitPeak),trail:n(a.assignedTrailBricks)};
}
function takeoverText(pos){const a=pos.renkoExitAssignment||assign(pos);return `🏁 <b>RENKO KÂR TAKİP STOPU DEVREDE</b>\n\n🔀 ${pos.sym} (${pos.yon})\n🧩 Pattern: ${pos.girisAnalizi?.patternKodu||'YOK'}\n📥 Atanan giriş: ${n(pos.girisAnalizi?.renkoEntryBrickDistance,0).toFixed(2)} tuğla\n🧱 Pozitif kâr koruması sonrası takip mesafesi: ${n(a.assignedTrailBricks).toFixed(2)} tuğla\n🛡️ İlk kâr koruma stopu: ${n(pos.renkoExitFirstProtectionStop,pos.sl)}\n🔄 Önceki exit: SHADOW\n🧠 Yeni yönetim: PATTERN BAZLI RENKO TRAILING STOP`;}
function closeId(pos,result){return String(pos?.closeId||pos?.tradeId||pos?.sanalOrderId||pos?.borsaOrderId||crypto.createHash('sha1').update([pos?.sym,pos?.yon,pos?.acilisZamani,result?.exitPrice,result?.reason].join('|')).digest('hex'));}
function replay(path,yon,entry,box,trail,activationPrice){let peak=activationPrice,exit=null,mfe=0;for(const row of path||[]){const p=n(row.price);if(!p)continue;const pnl=yon==='LONG'?(p-entry)/entry*100:(entry-p)/entry*100;mfe=Math.max(mfe,pnl);peak=yon==='LONG'?Math.max(peak,p):Math.min(peak,p);const stop=yon==='LONG'?peak-box*trail:peak+box*trail;if((yon==='LONG'&&p<=stop)||(yon==='SHORT'&&p>=stop)){exit=stop;break;}}if(exit==null)exit=n((path||[]).at(-1)?.price,activationPrice);const pct=yon==='LONG'?(exit-entry)/entry*100:(entry-exit)/entry*100;return {pct,mfe,capture:mfe>0?Math.max(0,Math.min(100,pct/mfe*100)):0};}
function close(pos,result={}){const s=read(),id=closeId(pos,result);if(s.processedIds[id]){s.health.duplicate++;write(s);return {accepted:false,reason:'DUPLICATE'};}if(result.restartGap){s.health.restartGap++;write(s);return {accepted:false,reason:'RESTART_GAP'};}if(/MANUAL_EXTERNAL_CLOSE|MANUAL_OVERRIDE/i.test(String(result.reason||''))){s.health.manualExcluded++;s.processedIds[id]={at:new Date().toISOString(),manual:true};write(s);return {accepted:false,reason:'MANUAL_EXCLUDED'};}
 const ga=pos.girisAnalizi||{}, box=n(ga.renkoBoxSize||pos.renkoBoxSize);if(!(box>0)||!pos.renkoExitActivated)return {accepted:false,reason:'NOT_ACTIVATED'};const k=key(pos.yon,ga.patternKodu),p=s.profiles[k]||(s.profiles[k]={patternKey:k,closed:0,activeTrail:DEFAULT_TRAIL(),candidates:{}});const path=pos?.execution?.pricePath||pos?.pricePath||[];for(const t of CANDIDATES()){const rr=replay(path,pos.yon,n(pos.girisFiyati),box,t,n(pos.renkoExitActivationPrice,pos.girisFiyati));const m=p.candidates[t]||(p.candidates[t]=blankMetric());m.samples++;m.net+=rr.pct;if(rr.pct>0){m.tp++;m.grossProfit+=rr.pct;}else if(rr.pct<0){m.sl++;m.grossLoss+=Math.abs(rr.pct);}else m.be++;m.mfeCaptureSum+=rr.capture;}
 p.closed++;const best=choose(p);if(best)p.activeTrail=best.trail;s.processedIds[id]={at:new Date().toISOString(),patternKey:k};write(s);fs.appendFileSync(LEDGER_FILE,JSON.stringify({type:'RENKO_EXIT_CLOSE',id,at:new Date().toISOString(),patternKey:k,result})+'\n');return {accepted:true,activeTrail:p.activeTrail};}
function summary(activePositions=[]){const s=read();const positions=Array.isArray(activePositions)?activePositions:[];const assigned=positions.filter(p=>p?.girisAnalizi?.entryStrategy==='ST2_RENKO'&&p?.renkoExitAssignment);const activated=assigned.filter(p=>p?.renkoExitActivated===true);const gap=assigned.filter(p=>p?.restartGap===true||p?.restartGapIslemi===true||p?.restartGapProtection===true);return {state:s,profiles:Object.values(s.profiles||{}).map(p=>({...p,activeMetric:metric(p.candidates?.[p.activeTrail]||blankMetric())})),runtime:{activeRenko:assigned.length,assigned:assigned.length,activated:activated.length,waiting:assigned.length-activated.length,restartGap:gap.length}};}
function telegram(activePositions=[]){const x=summary(activePositions);const totalClosed=x.profiles.reduce((a,p)=>a+n(p.closed),0);let t='🏁 <b>ST2 RENKO KÂR TAKİP STOPU EVRİMİ</b>\n━━━━━━━━━━━━━━━━━━\n';t+=`📊 Bilimsel kapanış: ${totalClosed} | Öğrenilmiş pattern: ${x.profiles.length}\n`;t+=`🧱 Takip profili atanmış: ${x.runtime.assigned} | 🟢 Takip stopu devrede: ${x.runtime.activated} | ⏳ Pozitif kâr koruması bekleyen: ${x.runtime.waiting}\n`;t+=`🛡️ Restart-GAP aktif: ${x.runtime.restartGap} | GAP öğrenme reddi: ${n(x.state.health?.restartGap)}\n`;t+=`🖐️ Manuel öğrenme dışı: ${n(x.state.health?.manualExcluded)} | Duplicate: ${n(x.state.health?.duplicate)}\n`;if(!x.profiles.length){t+=`\n⏳ Henüz bilimsel Renko takip stopu kapanışı yok. GAP olmayan ve pozitif kâr koruması sonrası takip stopu devreye giren işlemlerin kapanışı bekleniyor.\n`;t+=`⚙️ Başlangıç fallback: ${DEFAULT_TRAIL().toFixed(2)} tuğla | Adaylar: ${CANDIDATES().map(x=>x.toFixed(2)).join(' / ')}\n`;}
for(const pos of (activePositions||[]).filter(p=>p?.renkoExitAssignment)){const a=pos.renkoExitAssignment;t+=`\n🔀 ${pos.sym} ${pos.yon} | ${a.status==='ACTIVE'?'🟢 DEVREDE':'⏳ KORUMA BEKLİYOR'} | ${n(a.assignedTrailBricks).toFixed(2)} tuğla`;if(pos.renkoExitLastStopSourceLabel)t+=` | Stop kaynağı: ${pos.renkoExitLastStopSourceLabel}`;t+=`\n`;}
for(const p of x.profiles){t+=`\n🧩 ${p.patternKey} | Öğrenilmiş takip ${n(p.activeTrail).toFixed(2)} tuğla | N${n(p.closed)} | Net ${n(p.activeMetric.net).toFixed(4)} | PF ${n(p.activeMetric.pf).toFixed(2)} | Exp ${n(p.activeMetric.expectancy).toFixed(4)}\n`;for(const c of CANDIDATES()){const m=metric(p.candidates?.[c]||blankMetric());t+=`${c.toFixed(2)} | N${m.samples} | WR %${m.wr.toFixed(1)} | Net ${m.net>=0?'+':''}${m.net.toFixed(4)} | PF ${m.pf.toFixed(2)} | MFE %${m.mfeCapture.toFixed(1)}${c===p.activeTrail?' | ✅ AKTİF':''}\n`;}}return t;}
module.exports={VERSION,STATE_FILE,BACKUP_FILE,LEDGER_FILE,CANDIDATES,DEFAULT_TRAIL,activeFor,assign,update,takeoverText,close,summary,telegram,firstProtectionReady,peakProfitPct,mfeProtectionStop,stopSource,sourceLabel};
