'use strict';

// AGROS ST2 R26 CORE 15m CONFIRMED EVIDENCE
// Yalnız offline bootstrap + GERÇEK kapanmış DIRECT/CONFIRMED sonuçları.
// Counterfactual shadow lifecycle fiziksel olarak kaldırılmıştır.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const ayarlar = require('./ayarlar.js');
const VERSION = 'R26-CORE-15M-CONFIRMED-ACTUAL-EVIDENCE';
const DATA_DIR = process.env.AGROS_DATA_DIR ? path.resolve(process.env.AGROS_DATA_DIR) : path.join(__dirname,'data');
const STATE_FILE = path.join(DATA_DIR,'st2-15m-confirmed-evidence.json');
const BACKUP_FILE = `${STATE_FILE}.bak`;
let cache=null, persistScheduled=false, persistPromise=Promise.resolve();
function n(v,d=0){const x=Number(v);return Number.isFinite(x)?x:d;}
function blankMetric(){return {attempts:0,n:0,wins:0,losses:0,be:0,noEntry:0,net:0,grossProfit:0,grossLoss:0,lastAt:null};}
function blankState(){return {schema:3,version:VERSION,updatedAt:null,bootstrap:{meta:{status:'EMPTY',source:'15M_HISTORICAL_REPLAY',exact1mStModeled:false},profiles:{}},live:{profiles:{},processedCloseIds:{}},health:{loadErrors:0,saveErrors:0,duplicateClose:0}};}
function normalizeProfiles(obj){const out={};for(const[k,v]of Object.entries(obj||{}))out[k]={...blankMetric(),...(v||{})};return out;}
function hydrate(raw={}){const b=blankState();return {...b,...raw,schema:3,version:VERSION,bootstrap:{...b.bootstrap,...(raw.bootstrap||{}),meta:{...b.bootstrap.meta,...(raw.bootstrap?.meta||{})},profiles:normalizeProfiles(raw.bootstrap?.profiles)},live:{...b.live,...(raw.live||{}),profiles:normalizeProfiles(raw.live?.profiles),processedCloseIds:{...(raw.live?.processedCloseIds||{})}},health:{...b.health,...(raw.health||{})}};}
function ensureDir(){fs.mkdirSync(DATA_DIR,{recursive:true});}
function load(force=false){if(cache&&!force)return cache;ensureDir();for(const f of [STATE_FILE,BACKUP_FILE]){try{if(fs.existsSync(f)){cache=hydrate(JSON.parse(fs.readFileSync(f,'utf8')));return cache;}}catch(_){}}cache=blankState();return cache;}
function snapshot(){return JSON.parse(JSON.stringify(load()));}
function profileKey(mode,direction,pattern,offsetT){return `${String(mode||'').toUpperCase()}|${String(direction||'').toUpperCase()}|${String(pattern||'UNKNOWN').toUpperCase()}|${Number(offsetT).toFixed(2)}T`;}
function parseKey(key){const[mode,direction,pattern,offsetRaw]=String(key||'').split('|');return{mode,direction,pattern,offsetT:n(String(offsetRaw||'').replace('T',''))};}
function metric(raw={}){const x={...blankMetric(),...(raw||{})};const samples=n(x.n),gp=n(x.grossProfit),gl=n(x.grossLoss);return{...x,samples,wr:samples>0?n(x.wins)/samples*100:0,pf:gl>0?gp/gl:(gp>0?999:0),expectancy:samples>0?n(x.net)/samples:0};}
function observe(raw,result={}){const m=raw||blankMetric();m.attempts=n(m.attempts)+1;if(result.noEntry===true||result.triggered===false){m.noEntry=n(m.noEntry)+1;m.lastAt=result.at||new Date().toISOString();return m;}const pnl=n(result.netPct??result.pnlPct??result.net);m.n=n(m.n)+1;if(pnl>1e-12)m.wins=n(m.wins)+1;else if(pnl<-1e-12)m.losses=n(m.losses)+1;else m.be=n(m.be)+1;m.net=n(m.net)+pnl;if(pnl>=0)m.grossProfit=n(m.grossProfit)+pnl;else m.grossLoss=n(m.grossLoss)+Math.abs(pnl);m.lastAt=result.at||new Date().toISOString();return m;}
function scaleMetric(raw,maxWeight=Infinity){const m=metric(raw);if(!(m.samples>0)||!Number.isFinite(maxWeight)||m.samples<=maxWeight)return{...m,effectiveWeight:m.samples};const f=maxWeight/m.samples;return{...metric({...m,n:m.n*f,wins:m.wins*f,losses:m.losses*f,be:m.be*f,net:m.net*f,grossProfit:m.grossProfit*f,grossLoss:m.grossLoss*f,attempts:m.attempts*f,noEntry:m.noEntry*f}),rawSamples:m.samples,effectiveWeight:maxWeight};}
function combineMetrics(rows=[]){const o=blankMetric();for(const r of rows.filter(Boolean)){o.attempts+=n(r.attempts);o.n+=n(r.n,n(r.samples));o.wins+=n(r.wins);o.losses+=n(r.losses);o.be+=n(r.be);o.noEntry+=n(r.noEntry);o.net+=n(r.net);o.grossProfit+=n(r.grossProfit);o.grossLoss+=n(r.grossLoss);if(r.lastAt&&(!o.lastAt||String(r.lastAt)>String(o.lastAt)))o.lastAt=r.lastAt;}return metric(o);}
function rowsFor(sectionName,mode,direction,pattern=null){const profiles=load()?.[sectionName]?.profiles||{};const out=[];for(const[key,raw]of Object.entries(profiles)){const p=parseKey(key);if(p.mode!==String(mode).toUpperCase()||p.direction!==String(direction).toUpperCase())continue;if(pattern&&p.pattern!==String(pattern).toUpperCase())continue;out.push({key,...p,raw,metric:metric(raw)});}return out;}
function aggregateByOffset(sectionName,mode,direction,pattern=null,maxWeight=Infinity){const g=new Map();for(const row of rowsFor(sectionName,mode,direction,pattern)){const k=row.offsetT.toFixed(2);const list=g.get(k)||[];list.push(Number.isFinite(maxWeight)?scaleMetric(row.raw,maxWeight):metric(row.raw));g.set(k,list);}return[...g.entries()].map(([k,list])=>({offsetT:Number(k),...combineMetrics(list)}));}
function evidence(mode,direction,pattern='UNKNOWN',options={}){const minSamples=Math.max(1,n(options.minSamples,15));const bootstrapCap=Math.max(0,n(options.bootstrapCap,n(ayarlar.renkoGiris15mBootstrapMaksAgirlik,30)));const exact=String(pattern||'UNKNOWN').toUpperCase();const build=scope=>{const p=scope==='EXACT_PATTERN'?exact:null;const boot=aggregateByOffset('bootstrap',mode,direction,p,bootstrapCap);const live=aggregateByOffset('live',mode,direction,p,Infinity);const offsets=[...new Set([...boot,...live].map(x=>x.offsetT))].sort((a,b)=>a-b);return offsets.map(offsetT=>{const b=boot.find(x=>x.offsetT===offsetT),l=live.find(x=>x.offsetT===offsetT);return{mode:String(mode).toUpperCase(),direction:String(direction).toUpperCase(),pattern:p||'*',offsetT,evidenceScope:scope,evidenceTimeframe:'15M_CLOSED_RENKO_REVERSAL',bootstrapExact1mStModeled:load().bootstrap?.meta?.exact1mStModeled===true,bootstrap:b||metric({}),live:l||metric({}),...combineMetrics([b,l])};});};const exactRows=build('EXACT_PATTERN'),directionRows=build('DIRECTION_FALLBACK');const matureExact=exactRows.filter(x=>x.samples>=minSamples),matureDirection=directionRows.filter(x=>x.samples>=minSamples);const source=matureExact.length?matureExact:matureDirection.length?matureDirection:exactRows.length?exactRows:directionRows;return[...source].sort((a,b)=>b.expectancy-a.expectancy||b.wr-a.wr||b.pf-a.pf||b.samples-a.samples||a.offsetT-b.offsetT)[0]||{mode:String(mode).toUpperCase(),direction:String(direction).toUpperCase(),pattern:exact,offsetT:n(ayarlar.renkoGirisTeyitVarsayilanTugla,.25),evidenceScope:'NO_DATA',evidenceTimeframe:'15M_CLOSED_RENKO_REVERSAL',bootstrap:metric({}),live:metric({}),...metric({})};}
async function atomicPersist(state){ensureDir();const tmp=`${STATE_FILE}.${process.pid}.${Date.now()}.tmp`;try{if(fs.existsSync(STATE_FILE))await fs.promises.copyFile(STATE_FILE,BACKUP_FILE).catch(()=>{});await fs.promises.writeFile(tmp,JSON.stringify({...state,version:VERSION,updatedAt:new Date().toISOString()},null,2));await fs.promises.rename(tmp,STATE_FILE);}catch(e){state.health.saveErrors=n(state.health.saveErrors)+1;try{await fs.promises.unlink(tmp);}catch(_){}console.error(`⚠️ [15M CONFIRMED EVIDENCE SAVE] ${e.message}`);}}
function schedulePersist(){if(persistScheduled)return;persistScheduled=true;setImmediate(()=>{persistScheduled=false;const state=snapshot();persistPromise=persistPromise.then(()=>atomicPersist(state));});}
function closeId(pos,result={}){return String(pos?.tradeId||pos?.sanalOrderId||pos?.borsaOrderId||result.tradeId||crypto.createHash('sha1').update(`${pos?.sym}|${pos?.yon}|${pos?.acilisZamani}|${result.closedAt||Date.now()}`).digest('hex').slice(0,20));}
function recordLiveClose(pos,result={}){const ga=pos?.girisAnalizi||{};if(String(ga.entryStrategy||pos?.entryStrategy||'').toUpperCase()!=='ST2_RENKO')return{accepted:false,reason:'NOT_ST2_RENKO'};const mode=String(ga.entryMode||ga.entryModeDecision?.selectedMode||'').toUpperCase();if(!['DIRECT','CONFIRMED'].includes(mode))return{accepted:false,reason:'MODE_UNKNOWN'};if(mode==='CONFIRMED'&&!String(ga.entryTimingAuthority||'').includes('15M'))return{accepted:false,reason:'CONFIRMED_NOT_15M_AUTHORITY'};const direction=String(pos?.yon||ga.yon||'').toUpperCase(),pattern=String(ga.patternKodu||ga.patternCode||pos?.patternKodu||'UNKNOWN').toUpperCase(),offsetT=n(ga.entryModeOffsetT,n(ga.renkoEntryBrickDistance,0));if(!(offsetT>0)||!['LONG','SHORT'].includes(direction))return{accepted:false,reason:'PROFILE_INVALID'};const state=load(),id=closeId(pos,result);if(state.live.processedCloseIds[id]){state.health.duplicateClose=n(state.health.duplicateClose)+1;return{accepted:false,reason:'DUPLICATE_CLOSE',id};}const key=profileKey(mode,direction,pattern,offsetT);state.live.profiles[key]||=blankMetric();observe(state.live.profiles[key],{triggered:true,netPct:n(result.netPct),at:result.at||new Date().toISOString()});state.live.processedCloseIds[id]=result.at||new Date().toISOString();schedulePersist();return{accepted:true,id,key,metric:metric(state.live.profiles[key])};}
function replaceBootstrap(profiles={},meta={}){const state=load();state.bootstrap={meta:{...state.bootstrap.meta,...meta,status:meta.status||'READY',updatedAt:new Date().toISOString()},profiles:Object.fromEntries(Object.entries(profiles||{}).map(([k,v])=>[k,{...blankMetric(),...(v||{})}]))};cache=state;return state;}
async function saveNow(){await atomicPersist(load());return snapshot();}
function summary(){const s=load();return{version:VERSION,stateFile:STATE_FILE,bootstrap:s.bootstrap.meta,bootstrapProfiles:Object.keys(s.bootstrap.profiles||{}).length,liveProfiles:Object.keys(s.live.profiles||{}).length,liveCloses:Object.values(s.live.profiles||{}).reduce((a,x)=>a+n(x.n),0),health:s.health};}
function resetForTest(raw=null){cache=raw?hydrate(raw):blankState();persistScheduled=false;persistPromise=Promise.resolve();return cache;}
async function flushForTest(){await new Promise(r=>setImmediate(r));await persistPromise;}
module.exports={VERSION,STATE_FILE,BACKUP_FILE,load,snapshot,summary,profileKey,parseKey,metric,observe,evidence,recordLiveClose,replaceBootstrap,saveNow,_blankState:blankState,_blankMetric:blankMetric,_combineMetrics:combineMetrics,_resetForTest:resetForTest,_flushForTest:flushForTest};
