'use strict';

// AGROS ST2 v6.14.0-R26 CORE-ONLY CONFIGURATION
// Yalnız canlı çekirdeğin gerçekten okuduğu ayarlar tutulur.

const ayarlar = {
    "binanceAgEszamanlilik": 3,
    "binanceAgIsciSayisi": 8,
    "binanceAgRetry": 2,
    "binanceAgRetryTabanMs": 900,
    "binanceAgTimeoutMs": 15000,
    "binanceSignedRecvWindowMs": 15000,
    "binanceStartupAgEszamanlilik": 4,
    "binanceStartupAgIsciSayisi": 4,
    "binanceStartupNetworkConcurrency": 4,
    "binanceStartupRepairRequestRetry": 1,
    "binanceStartupRepairRequestRetryTabanMs": 700,
    "binanceStartupRepairRequestTimeoutMs": 8000,
    "binanceStartupRepairSymbolDeadlineMs": 40000,
    "binanceStartupRequestRetry": 0,
    "binanceStartupRequestRetryTabanMs": 500,
    "binanceStartupRequestTimeoutMs": 7000,
    "binanceStartupSymbolDeadlineMs": 20000,
    "binanceTimeMaxAgeMs": 600000,
    "binanceTimeSyncIntervalMs": 300000,
    "binanceTimeSyncSamples": 3,
    "binanceTimeSyncTimeoutMs": 5000,
    "binanceTopluVeriRetryMs": 90000,
    "blackboxBollingerTf": "15m",
    "blackboxRequestTimeoutMs": 5000,
    "blackboxSnapshotTimeoutMs": 7000,
    "blackboxTimeframes": [
        "5m",
        "15m",
        "1h",
        "4h"
    ],
    "bollingercarpani": 2,
    "bollingerperiod": 20,
    "calisilmakIstenenUsdtMiktar": 4,
    "canliRaporAktif": true,
    "canliRaporEskiMesajiSil": true,
    "canliRaporGuncellemeMs": 30000,
    "canliRaporYenidenGondermeMs": 180000,
    "confirmedYuzdeselEkonomiAdimYuzde": 0.5,
    "confirmedYuzdeselEkonomiAktif": true,
    "confirmedYuzdeselEkonomiAktivasyonYuzde": 1.5,
    "confirmedYuzdeselEkonomiIlkKilitYuzde": 1,
    "confirmedYuzdeselEkonomiTakipMesafeYuzde": 0.5,
    "entryStrategyMode": "ST2_DUAL_REAL",
    "heikinAshiAktif": true,
    "heikinAshiBandYakinlikYuzdesi": 0.5,
    "heikinAshiBollingerCarpani": 2,
    "heikinAshiBollingerPeriod": 20,
    "heikinAshiFormasyonAktif": true,
    "heikinAshiFormasyonVetoAktif": true,
    "heikinAshiFormasyonBakisMum": 64,
    "heikinAshiFormasyonVetoSkor": 70,
    "heikinAshiStructureAuthorityAktif": true,
    "heikinAshiStructureMinQuality": 64,
    "heikinAshiFormationOrGateAktif": true,
    "heikinAshiFinalSuperTrendAktif": true,
    "heikinAshiFinalSuperTrendPeriyodu": "3m",
    "heikinAshiFinalSuperTrendPeriod": 10,
    "heikinAshiFinalSuperTrendMultiplier": 3,
    "heikinAshiBbRegimeBakisMum": 80,
    "heikinAshiBbNarrowPercentile": 28,
    "heikinAshiBbWidePercentile": 72,
    "heikinAshiBbExtremePercentile": 90,
    "heikinAshiCupBuyukBakisMum": 80,
    "heikinAshiCupKucukBakisMum": 28,
    "heikinAshiButterflyMinScore": 72,
    "heikinAshiButterflyMaxPrzAtr": 0.9,
    "heikinAshiButterflyMaxDAge": 4,
    "heikinAshiFormasyonKanitiTelegram": true,
    "heikinAshiGercekMaxAktifPozisyon": 10,
    "heikinAshiMaxPusuBeklemeMum": 3,
    "heikinAshiTetikPenceresiMum": 1,
    "heikinAshiPeriyodu": "15m",
    "futuresTickerRetry": 0,
    "futuresTickerTimeoutMs": 6000,
    "gercekDirectIzinliTuglalar": [
        0.5,
        1
    ],
    "gercekDirectTuglaFiltreAktif": true,
    "gercekEmirAnaAgZorunlu": true,
    "gercekEmirKaldiracFallbackAktif": false,
    "gercekEmirKorumaEmirleriZorunlu": true,
    "gercekEmirLotSizeAsagiSapmaYuzde": 5,
    "gercekEmirMaksNotionalSapmaYuzde": 2,
    "gercekEmirMarjinTipi": "ISOLATED",
    "gercekEmirMaxAktifPozisyon": 20,
    "renkoGercekMaxAktifPozisyon": 10,
    "gercekEmirOnayKodu": "LIVE_TRADING_CONFIRMED",
    "gercekEmirYetkilendirmeAktif": true,
    "gercekPozisyonMutabakatTimeoutMs": 8000,
    "gercekStopMinGuncellemeAralikMs": 3000,
    "gunlukMaxYeniEmir": 0,
    "kaliciHafizaLogAktif": true,
    "kapanmisMumYayinGecikmesiMs": 3000,
    "n5CanliEkonomiAktif": true,
    "n5MinExpectancy": 0,
    "n5MinKapanis": 5,
    "n5MinNet": 0,
    "n5MinPF": 1,
    "n5GercekEmirYetkisi": true,
    "manuelKapanisYenidenGirisKilidiMs": 3600000,
    "maxPusuBeklemeTugla": 3,
    "maxTpYuzdesi": 50,
    "mevcutKaldirac": 5,
    "pingInterval": 1000,
    "premierScoreOosCoinVetoAktif": true,
    "premierScoreOosCoinVetoBits": [
        "1000",
        "1001"
    ],
    "pusuPeriyodu": "15m",
    "pusuVeriTazelemeMs": null,
    "renkoAtrPeriod": 14,
    "renkoAuditLogMs": 60000,
    "renkoBbTemasToleransTugla": 0.25,
    "renkoBollingerPeriod": 20,
    "renkoCanliTaramaMaxTugla": 128,
    "renkoEventLoopStarvationLogMs": 1000,
    "renkoGiris15mBootstrapMaksAgirlik": 30,
    "renkoGirisAdayTugla": [
        0.25,
        0.5,
        0.75,
        1,
        1.25,
        1.5
    ],
    "renkoGirisGuncelAgirlik": 0.65,
    "renkoGirisGuncelPencere": 10,
    "renkoGirisIlkAtamaKapanis": 3,
    "renkoGirisMinSkorIyilesme": 0.005,
    "renkoGirisModuMinBasariYuzde": 75,
    "renkoGirisModuMinExpAvantaj": 0,
    "renkoGirisModuMinOrnek": 20,
    "renkoGirisModuMinTeyitOrnek": 15,
    "renkoGirisModuMinWrAvantaj": 2,
    "renkoGirisModuOtomatikAktif": true,
    "renkoGirisModuZorlaConfirmed": true,
    "renkoGirisOgrenmeAktif": true,
    "renkoGirisOtomatikAktiflestirme": true,
    "renkoGirisTeyitVarsayilanTugla": 0.25,
    "renkoGirisVarsayilanTugla": 0.75,
    "renkoGirisYenidenHesaplamaAdimi": 5,
    "renkoKanitTuglaSayisi": 10,
    "renkoKaynakMumLimiti": 250,
    "renkoKaynakPeriyodu": "15m",
    "renkoOnayAtrPeriod": 14,
    "renkoOnayDerinOnarimMumLimiti": 240,
    "renkoOnayIncrementalMumMax": 30,
    "renkoOnayIncrementalMumMin": 5,
    "renkoOnayKaynakMumLimiti": 80,
    "renkoOnayMaksOnarimMumLimiti": 480,
    "renkoOnayPeriyodu": "1m",
    "renkoOnayRefreshRetry": 0,
    "renkoOnayRefreshTimeoutMs": 6000,
    "renkoOnaySuperTrendMultiplier": 3,
    "renkoOnaySuperTrendPeriod": 10,
    "renkoPremierScoreGoreceliYuzdelik": 0.4,
    "renkoPremierScoreMaxDinamikEsik": 70,
    "renkoPremierScoreMin": 55,
    "renkoPremierScoreMinOrnek": 3,
    "renkoProofConsoleAktif": false,
    "renkoPusuBildirimHafizaMax": 5000,
    "renkoPusuBildirimHafizaSaat": 168,
    "renkoPusuKanitTelegram": true,
    "renkoPusuStartupTekrarBastirMs": 900000,
    "renkoRuntimeYieldEverySembol": 2,
    "renkoSlowSymbolLogMs": 1000,
    "renkoTarihselPremierMinN": 5,
    "renkoTetikYuzdesi": 0.05,
    "renkoYakinRedKanitSayisi": 3,
    "sabitStopYuzdesi": 2.5,
    "sabitTpYuzdesi": 0.4,
    "sanalEmirModu": false,
    "sniperPeriyodu": "1m",
    "st2ExchangeReconcileFreshMs": 15000,
    "st2ExchangeReconcileIntervalMs": 5000,
    "st2MainLoopWatchdogLogAralikMs": 30000,
    "st2MainLoopWatchdogMs": 20000,
    "st2StartupProtectionIntervalMs": 5000,
    "startupMarketGuardLogAralikMs": 60000,
    "startupMarketReadyOrani": 0.95,
    "stopBildirimMinSaniye": 0,
    "stopTakipModu": "KADEME",
    "superTrendMultiplier": 3,
    "superTrendPeriod": 10,
    "superTrendPeriyodu": "3m",
    "superTrendTazelemeMs": null,
    "taranacakCoinSayisi": 200,
    "telegramAcilisPusuMaxSatir": 6,
    "telegramCanliPanelTimeoutMs": 6000,
    "telegramIslemAcilisMesaji": true,
    "telegramMesajMaxKarakter": 3400,
    "telegramMinimalOperasyonModu": true,
    "telegramStopGuncellemeMesaji": false,
    "trendPeriyodu": "3m"
};

ayarlar.renkoDnaSon3MinNetFarki = Number(process.env.AGROS_RENKO_DNA_LAST3_MIN_NET_EDGE || 0.10);
ayarlar.renkoDnaSon3MinOransalFark = Number(process.env.AGROS_RENKO_DNA_LAST3_MIN_RELATIVE_EDGE || 0.15);

module.exports = ayarlar;
