'use strict';
const assert = require('assert');
const fs = require('fs');
const bot = fs.readFileSync('bot.js', 'utf8');
const memory = fs.readFileSync('1_hafiza.js', 'utf8');
const entry = fs.readFileSync('73_st2_renko_entry_evolution.js', 'utf8');
const version = require('./versiyon.js');
assert.ok(bot.includes('telegramMesajGonderHizli(baslangicMesaji)'), 'startup fast Telegram path missing');
assert.ok(bot.includes("setImmediate(() =>"), 'startup reporting must run in background');
assert.ok(bot.includes("const basarili = Array.isArray(sonuclar)"), 'success-only startup stamp guard missing');
assert.ok(bot.includes("Gönderim doğrulanmadı; startup damgası yazılmadı"), 'failed startup stamp audit missing');
assert.ok(bot.includes('Promise.resolve(rapor.raporGonder(false))'), 'periodic live report must be non-blocking');
assert.ok(bot.includes('canliRaporCalisiyor'), 'background live report overlap guard missing');
assert.ok(memory.includes('telegramMesajGonderHizli'), 'fast Telegram API missing');
assert.ok(memory.includes('{ timeoutMs: 8000, retryCount: 0 }'), 'startup Telegram fast policy mismatch');
assert.ok(entry.includes("PATTERN GİRİŞ EVRİMİNDE N5'E EN YAKIN"), 'truthful pattern-level heading missing');
assert.ok(!entry.includes("<b>PREMIER'E EN YAKIN</b>"), 'misleading Premier heading still present');
assert.ok(/^6\.3\.(5|6|7|8|9)-/.test(version.botSurumu));
console.log('✅ v6.3.5 non-blocking Telegram startup + success-only stamp + truthful pattern heading passed');
