'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const source=fs.readFileSync(path.join(__dirname,'73_st2_renko_entry_evolution.js'),'utf8');
assert(source.includes('BAŞARISIZ PATTERN DAĞILIMI'));
assert(source.includes('.filter(r=>n(r.cur.sl)>0)'));
assert(source.includes('Başarısız mutabakatı:'));
assert(source.includes('fail===failedCheck'));
assert(source.includes('r0.p.patternCode'));
assert(source.includes('Giriş ${n(r0.p.activeBrick'));
assert(source.includes('✅${n(r0.cur.tp)} ❌${n(r0.cur.sl)}'));
assert(source.includes('WR %${wr0.toFixed(1)}'));
assert(source.includes('Net ${n(r0.cur.net)>=0'));
assert(source.includes('PF ${n(r0.cur.pf).toFixed(2)}'));
console.log('✅ v5.6.10 failed-pattern breakdown + reconciliation passed');
