const assert=require('assert');
const ops=require('./69_operation_intelligence_dashboard.js');
const strong=ops.componentScore({historical:{total:30,net:8,expectancy:.25,profitFactor:2},liveMetrics:{closed:6,net:2,expectancy:.33,profitFactor:2},exitValidated:true},null);
const weak=ops.componentScore({historical:{total:10,net:-3,expectancy:-.3,profitFactor:.4},liveMetrics:{closed:5,net:-2,expectancy:-.4,profitFactor:.3},exitValidated:false,safeFallback:true},null);
assert(strong.score>weak.score,'positive evidence must rank above negative evidence');
const metric={opened:6,active:0,closed:5,tp:3,sl:1,be:1,net:1.2,profitFactor:2,expectancy:.24};
const prebuilt={model:{aggregate:metric,trackMetrics:{reverse:metric},league:{historicalPositiveCount:40,reversePremierCount:20,labLeagueCount:745,nearProfitCount:13},accounting:{activeScientific:0,activeGap:0,reconciled:true}},premier:[{labDnaLabel:'LAB #67',selectionI2:{score:88},form:'📈 GÜÇLENİYOR',liveMetrics:metric}],reverse:[],candidates:[{sourceLabDnaLabel:'LAB #379',reverseTargetLabDnaLabel:'LAB #873',liveMetrics:metric}],changes:{strengthening:1,weakening:0,exitChanges:1,stopReady:2,beReady:1,reverseCandidates:1}};
const text=ops.telegram([],prebuilt);
for(const token of ['AGROS OPERASYON MERKEZİ','NEGATIVE LEAGUE SONUÇ DEFTERİ','PREMIER KARAR VE FORM ÖZETİ','AGROS YORUMU','Trade Engine']) assert(text.includes(token),token);
console.log('✅ v5.3.5 Live Operations + Negative Ledger + advisory Selection Intelligence 2.0 tests passed');
