const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync(require.resolve('./47_dynamic_dna_exit_engine.js'),'utf8');
assert(src.includes('modelCacheStamp'));
assert(src.includes('readModelCached'));
assert(src.includes('maxBytes:64*1024*1024'));
const obs=fs.readFileSync(require.resolve('./48_premier_observation_engine.js'),'utf8');
assert(obs.includes("require('./53_memory_safe_io.js')"));
assert(obs.includes('maxBytes: 32 * 1024 * 1024'));
console.log('✅ v4.5.7 memory guard contract passed');
