'use strict';
const fs=require('fs');
const os=require('os');
const path=require('path');
const assert=require('assert');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'agros-v632-'));
process.env.AGROS_DATA_DIR=dir;
const canonical=require('./80_st2_canonical_historical_pool.js');
const symbols={};for(const sym of canonical.SYMBOLS)symbols[sym]={signals:1};
fs.writeFileSync(path.join(dir,'st2-historical-training.json'),JSON.stringify({symbols,profiles:{}},null,2));
function event(i,{yon='SHORT',patternCode='S01',bb='UST',bbw='COK_GENIS',renko6='GGGGGG',atr='NORMAL',trend='UP',session='ABD',pnl=0.2}={}){
  return {type:'HISTORICAL_SIGNAL',yon,patternCode,context:{renko6,session,features:[`BB=${bb}`,`BBW=${bbw}`,`RENKO6=${renko6}`,`ATR=${atr}`,`TREND20=${trend}`,`SESSION=${session}`]},candidates:{'1.50':{triggered:true,resolved:true,pnlPct:pnl}}};
}
const lines=[];
for(let i=0;i<8;i++)lines.push(JSON.stringify(event(i)));
for(let i=0;i<6;i++)lines.push(JSON.stringify(event(i,{bb:'ORTA_UST',pnl:-0.2})));
fs.writeFileSync(path.join(dir,'st2-historical-training-ledger.jsonl'),lines.join('\n')+'\n');
const adaptive=require('./76_st2_adaptive_dna_entry.js');
const intel=require('./77_st2_pattern_dna_intelligence.js');
const strong={yon:'SHORT',patternKodu:'S01',rbb:'UST',rbbw:'COK_GENIS',renko6:'GGGGGG',atrRegime:'NORMAL',trend20:'UP',session:'ABD'};
let g=adaptive.gateDecision(strong,0.75);
assert.equal(g.allow,true,'strong exact historical DNA must open Premier');
assert.equal(g.executionMode,'PREMIER');
assert.equal(g.reason,'HISTORICAL_EXACT_DNA_PREMIER');
const unknown={...strong,rbb:'ALT'};
g=adaptive.gateDecision(unknown,0.75);
assert.equal(g.allow,false,'unknown exact DNA must not borrow nearest/pattern authority');
assert.equal(g.executionMode,'SHADOW');
assert.equal(g.reason,'EXACT_DNA_UNSEEN_SHADOW');
const negative={...strong,rbb:'ORTA_UST'};
g=adaptive.gateDecision(negative,0.75);
assert.equal(g.allow,false,'negative exact DNA must remain Shadow');
assert.equal(g.executionMode,'SHADOW');
assert.equal(g.reason,'HISTORICAL_EXACT_DNA_NEGATIVE_SHADOW');
let s=adaptive.load();
const c=adaptive.contextFrom(strong),key=adaptive.dnaKey(c);
s.dnaProfiles[key]={key,patternKey:adaptive.patternKey(c),context:c,activeBrick:1.5,liveCandidate:null,lastDecision:'TEST',changes:[],closes:[0,1,2].map(i=>({at:new Date().toISOString(),tradeId:`t${i}`,candidates:{'1.50':{triggered:true,net:-0.2}}}))};
adaptive.save(s);
g=adaptive.gateDecision(strong,0.75);
assert.equal(g.allow,false,'completed losing live N3 must demote historical Premier to Shadow');
assert.equal(g.reason,'LIVE_N3_DEMOTED_TO_SHADOW');
const sum=adaptive.summary();
assert.equal(sum.health.historicalPremierProfiles,1,'exact positive historical Premier count must be truthful');
assert.ok(sum.health.historicalProfiles>=2);
const reg=intel.registry();
assert.ok(reg.profiles.every(p=>p.confidence.regimeCompleteness<=100),'confidence components must be normalized to 100');
const text=intel.telegram(20);
assert.ok(text.includes('Güçlü exact tarihsel DNA doğrudan Premier'));
assert.ok(text.includes('En yakın DNA Premier yetkisi YOK'));
console.log('✅ v6.3.2 exact DNA Premier + Shadow learning reconciliation passed');
