'use strict';
const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'agros-v602-'));
process.env.AGROS_DATA_DIR=tmp;
const events=[];
for(const zone of ['ALT','ORTA_ALT']){
  for(let i=0;i<3;i++)events.push({type:'HISTORICAL_SIGNAL',yon:'LONG',patternCode:'RRRR',context:{features:[`BB=${zone}`,'BBW=NORMAL','ATR=NORMAL','TREND20=UP','SESSION=ASYA','RENKO6=GRRRRR'],session:'ASYA',renko6:'GRRRRR'},candidates:{'0.25':{triggered:true,resolved:true,pnlPct:-0.05},'1.00':{triggered:true,resolved:true,pnlPct:0.20}}});
}
for(let i=0;i<5;i++)events.push({type:'HISTORICAL_SIGNAL',yon:'SHORT',patternCode:'GGGG',context:{features:['BB=UST','BBW=NORMAL','ATR=NORMAL','TREND20=DOWN','SESSION=ABD','RENKO6=RGGGGG'],session:'ABD',renko6:'RGGGGG'},candidates:{'0.50':{triggered:true,resolved:true,pnlPct:-0.15},'1.25':{triggered:true,resolved:true,pnlPct:0.18}}});
fs.writeFileSync(path.join(tmp,'st2-historical-training-ledger.jsonl'),events.map(JSON.stringify).join('\n')+'\n');
const adaptive=require('./76_st2_adaptive_dna_entry.js');
const longPos={yon:'LONG',girisAnalizi:{patternKodu:'RRRR',renkoSonTuglaDizisi:'GRRRRR',renkoBb:{zone:'ALT',widthRegime:'NORMAL'},atrRegime:'NORMAL',trend20:'UP',session:'ASYA'}};
const idx=adaptive.buildHistoricalIndex();
assert(idx.patterns['LONG|RRRR'],'LONG|RRRR aggregate edilmelidir');
assert(idx.patterns['SHORT|GGGG'],'SHORT|GGGG aggregate edilmelidir');
assert.equal(idx.patterns['LONG|RRRR'].n,6);
assert.equal(idx.patterns['LONG|RRRR'].brick,1.00);
const selected=adaptive.select(longPos,0.75);
assert.equal(selected.brick,1.00,'N3 exact DNA yerine N6 pattern toplamı kullanılmalıdır');
assert.equal(selected.historical.source,'HISTORICAL_PATTERN_LEDGER');
let premier=adaptive.premierFor(longPos);
assert.equal(premier.premier,true);
assert.equal(premier.reason,'HISTORICAL_WINNER_READY');
assert.equal(premier.closed,6);
assert.equal(premier.activeBrick,1.00);
const c=adaptive.contextFrom(longPos), key=adaptive.dnaKey(c);
const bad={schema:2,version:adaptive.VERSION,updatedAt:new Date().toISOString(),dnaProfiles:{[key]:{key,patternKey:'LONG|RRRR',context:c,activeBrick:1.00,closes:[0,1,2].map(i=>({at:new Date().toISOString(),tradeId:`bad-${i}`,candidates:{'1.00':{net:-0.2,triggered:true},'0.25':{net:-0.1,triggered:true}}})),changes:[]}},history:[],health:{observed:3,duplicates:0,lastTradeId:'bad-2'}};
fs.writeFileSync(path.join(tmp,'st2-adaptive-pattern-dna-entry.json'),JSON.stringify(bad));
premier=adaptive.premierFor(longPos);
assert.equal(premier.premier,false,'canlı son-3 zarar tarihsel Premieri durdurmalıdır');
assert.equal(premier.reason,'LIVE_LAST3_NOT_PROFITABLE');
console.log('✅ v6.0.2 Complete Historical Premier passed | all pattern aggregation + best entry + live loser stop');
