'use strict';
const assert=require('assert'); const fs=require('fs'); const os=require('os'); const path=require('path');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'agros-v564-')); process.env.AGROS_DATA_DIR=tmp;
for(const k of Object.keys(require.cache)) if(k.includes('74_st2_renko_exit_evolution')) delete require.cache[k];
const evo=require('./74_st2_renko_exit_evolution.js');
const pos={sanalOrderId:'T1',sym:'XXXUSDT',yon:'LONG',girisFiyati:100,sl:98,breakevenAktif:false,girisAnalizi:{patternKodu:'RRRR',renkoBoxSize:1,renkoEntryBrickDistance:.5},execution:{pricePath:[{price:100},{price:101},{price:102},{price:103},{price:102}]}};
const a=evo.assign(pos); assert.equal(a.assignedTrailBricks,1); assert.equal(a.status,'WAITING_SAFE_START');
let u=evo.update(pos,101); assert.equal(u.active,false,'ilk koruma öncesi devralmamalı');
pos.breakevenAktif=true; pos.korunanKarYuzdesi=.2; pos.sl=100.2;
u=evo.update(pos,102); assert.equal(u.active,true); assert.equal(pos.renkoExitActivated,true); assert(pos.sl>=100.2,'Renko stop ilk koruma altına inemez');
const old=pos.sl; evo.update(pos,103); assert(pos.sl>=old,'stop geriye gidemez');
let c=evo.close(pos,{reason:'RENKO_TRAIL_STOP',exitPrice:pos.sl,outcome:'TP'}); assert.equal(c.accepted,true);
c=evo.close(pos,{reason:'RENKO_TRAIL_STOP',exitPrice:pos.sl,outcome:'TP'}); assert.equal(c.reason,'DUPLICATE');
const manual={...pos,sanalOrderId:'T2'}; c=evo.close(manual,{reason:'MANUAL_EXTERNAL_CLOSE',exitPrice:101}); assert.equal(c.reason,'MANUAL_EXCLUDED');
const source=fs.readFileSync(path.join(__dirname,'4_pozisyon.js'),'utf8');
assert(source.includes('MANUAL_EXTERNAL_CLOSE')); assert(source.includes('renkoExitEvolution.update')); assert(source.includes('renkoExitTakeoverNotified'));
const motor=fs.readFileSync(path.join(__dirname,'motor.js'),'utf8'); assert(motor.includes('renkoExitEvolution.assign(yeniPozisyon)'));
console.log('✅ v5.6.4 Renko exit assignment + safe takeover + manual close safety passed');
