'use strict';
const assert=require('assert'); const fs=require('fs'); const path=require('path');
const tmp=path.join(__dirname,'.tmp-v650-mfe-capture'); fs.rmSync(tmp,{recursive:true,force:true}); fs.mkdirSync(tmp,{recursive:true}); process.env.AGROS_DATA_DIR=tmp;
const evo=require('./74_st2_renko_exit_evolution.js');
assert(['v6.5.0-MFE-CAPTURE-TAKEOVER-EVOLUTION','v6.6.0-LEARNED-TAKEOVER-EXPLAINABLE-PROTECTION','v6.6.1-PREMIER-TRUTH-PROTECTION-LOCK'].includes(evo.VERSION));
assert.deepEqual(evo.TAKEOVER_CANDIDATES(),[0.25,0.4,0.5,0.75,1,1.25]);
const pathRows=[100,100.3,100.6,101.0,101.5,101.2,100.9].map((price,i)=>({price,at:new Date(1700000000000+i*60000).toISOString()}));
const rr=evo.replay(pathRows,'LONG',100,0.25,1,0.5,100.9);
assert(rr.activated); assert(rr.mfe>=1.49); assert(rr.capture>0); assert(rr.giveback>=0);
const pos={sym:'TESTUSDT',yon:'LONG',girisFiyati:100,acilisZamani:new Date(1700000000000).toISOString(),renkoExitActivated:true,renkoExitActivatedAt:new Date(1700000120000).toISOString(),renkoExitActivationPrice:100.6,girisAnalizi:{entryStrategy:'ST2_RENKO',patternKodu:'RRRR',renkoBoxSize:0.25,renkoEntryBrickDistance:0.25},execution:{pricePath:pathRows},renkoExitAssignment:{assignedTrailBricks:1,patternKey:'LONG|RRRR'}};
const out=evo.close(pos,{exitPrice:100.9,fiyatKarYuzdesi:0.9,reason:'RENKO_TRAIL',restartGap:false});
assert(out.accepted); assert(out.audit.mfe>=1.49); assert(out.audit.capture>50); assert(out.audit.giveback>0);
const sum=evo.summary([]); assert.equal(sum.profiles.length,1); assert.equal(sum.profiles[0].closed,1); assert(sum.profiles[0].auditMetric.avgMfe>0);
const tg=evo.telegram([]); assert(tg.includes('MFE CAPTURE')); assert(tg.includes('Geri verme')); assert(tg.includes('Devralma'));
const dup=evo.close(pos,{exitPrice:100.9,fiyatKarYuzdesi:0.9,reason:'RENKO_TRAIL'}); assert.equal(dup.reason,'DUPLICATE');
console.log('✅ v6.5.0 MFE capture + takeover evolution + joint shadow replay passed');
