'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const read = f => fs.readFileSync(path.join(__dirname, f), 'utf8');
const report = read('2_rapor.js');
const renko = read('72_st2_renko_entry.js');
const dna = read('76_st2_adaptive_dna_entry.js');
const bot = read('bot.js');
const cfg = read('ayarlar.js');
const start = report.indexOf('function st2HafifCanliRaporMetniOlustur()');
const end = report.indexOf('function minimalCanliRaporMetniOlustur()', start);
assert(start >= 0 && end > start, 'ST2 RAM-only live panel function missing');
const light = report.slice(start, end);
for (const forbidden of ['renkoEntryEvolution.summary(', 'st2ReplayKatmanOzeti(', 'williamsCycleShadow.summary(', 'renkoEntryConfirmationShadow.summary(', 'operationIntelligence.build(', 'operationIntelligence.scientificLedgerPartitions(', 'adaptiveDnaEntry.summary(']) assert(!light.includes(forbidden), `30s ST2 panel must not run heavy live CPU function: ${forbidden}`);
assert(report.includes("if (ayarlar.entryStrategyMode === 'ST2_RENKO') return st2HafifCanliRaporMetniOlustur();"));
assert(light.includes('Panel CPU=RAM-ONLY'));
assert(dna.includes('let premierCohortCache={signature:null,value:null};'));
assert(dna.includes('if(premierCohortCache.signature===signature'));
assert(dna.includes('fileSig(ENTRY_EVOLUTION_STATE_FILE)'));
assert(dna.includes('fileSig(TAKEOVER_STATE_FILE)'));
assert(renko.includes('[ST2 EVENT LOOP STARVATION]'));
assert(renko.includes('| Expire ${tExpireMs} | BB ${tBbMs} | Pattern/DNA ${tPatternMs}'));
assert(/renkoRuntimeYieldEverySembol:\s*2/.test(cfg));
assert(bot.includes('h.state.st2RenkoScanInProgress = true;'));
assert(bot.includes('h.state.st2RenkoScanInProgress = false;'));
console.log('✅ v6.13.5-R19 live CPU isolation passed | 30s panel RAM-only + Premier cohort cache + 2-symbol event-loop fairness + full slow-stage observability');
