'use strict';
const assert = require('assert');
process.env.AGROS_DATA_DIR = require('path').join(__dirname, '.tmp-v559-dashboard');
const fs = require('fs'); fs.rmSync(process.env.AGROS_DATA_DIR,{recursive:true,force:true}); fs.mkdirSync(process.env.AGROS_DATA_DIR,{recursive:true});
const evo = require('./73_st2_renko_entry_evolution.js');
const text = evo.telegram();
assert(text.includes('Bilimsel kapanış'));
assert(text.includes('PRICE-PATH REPLAY'));
assert(text.includes('Başarılı'));
assert(text.includes('Başarısız'));
assert(text.includes("Premier şartını geçen"));
assert(text.includes('Varsayılan 0.75'));
assert(text.includes('KARAR ZİNCİRİ'));
assert(text.includes('Atanan'));
assert(text.includes('Uygulanan'));
assert(text.includes('0.25 | Tetik'));
console.log('✅ v5.5.9 ST2 Renko entry dashboard test passed');
