'use strict';
const fs=require('fs');
const assert=require('assert');
const report=fs.readFileSync('2_rapor.js','utf8');
const entry=fs.readFileSync('73_st2_renko_entry_evolution.js','utf8');
const dna=fs.readFileSync('77_st2_pattern_dna_intelligence.js','utf8');
const version=require('./versiyon.js');
assert.ok(/^6\.(3\.[3-9]|4.[012])-/.test(String(version.botSurumu||'')));
assert.ok(report.includes('Pusu DNA adayı'));
assert.ok(report.includes('Aktif Shadow kanıtı'));
assert.ok(entry.includes('legacyEntryAuditV632'));
assert.ok(entry.includes('PRE_V632_ABSOLUTE_PRICE_MATCH_AUDIT'));
assert.ok(dna.includes('Tarihsel lig ${league} | Güven sınıfı ${cf.grade}'));
console.log('✅ v6.3.3 final observability + audit reconciliation passed');
