const assert = require('assert');
const fs = require('fs');
const source = fs.readFileSync('62_lab_premier_league.js', 'utf8');
assert(source.includes("league: 'CHAMPIONSHIP', premierTrack: TRACK.RECENT5, upperLayerIncluded: false"), 'Recent5 must be outside Premier upper ledger');
assert(source.includes("observationEligible: Boolean(upperLayerIncluded || tier.premierTrack === TRACK.RECENT5)"), 'Recent5 must continue observation');
assert(source.includes("if (decision.upperLayerIncluded) { state.aggregate.opened++; state.aggregate.active++; }"), 'Only upper Premier may enter aggregate');
assert(source.includes("if (observation.upperLayerIncluded) applyClosed(state.aggregate"), 'Only upper Premier may close into aggregate');
assert(source.includes('SON-5 AYRI GÖLGE DEFTERİ'), 'Telegram must show separate Recent5 ledger');
assert(source.includes('Premier aktif/net/PF hesabına dahil değildir'), 'Telegram must explain exclusion');
console.log('✅ v5.2.1 Recent-5 separate shadow ledger contract passed');
