'use strict';
const fs=require('fs');
const assert=require('assert');
const h=fs.readFileSync('./1_hafiza.js','utf8');
const r=fs.readFileSync('./78_st2_global_historical_reconciliation.js','utf8');
const rt=fs.readFileSync('./79_st2_global_historical_runtime.js','utf8');
const canonical=require('./80_st2_canonical_historical_pool.js');
assert(h.includes('AGROS_ST2_TELEGRAM_TIMEOUT_MS || 30000'));
assert(h.includes('AGROS_ST2_TELEGRAM_RETRY_COUNT || 2'));
assert(h.includes('telegramKuyruk'));
assert(h.includes('TELEGRAM_MIN_INTERVAL_MS'));
assert.strictEqual(canonical.COINS.length,29);
assert.strictEqual(canonical.SYMBOLS.length,29);
assert(!canonical.COINS.includes('PEPE'));
assert(r.includes("require('./80_st2_canonical_historical_pool.js')"));
assert(r.includes('const COINS=canonicalPool.COINS'));
assert(rt.includes('CANONICAL_COIN_POOL_INVALID'));
console.log('✅ v6.2.1 Telegram resilience + shared canonical 29-coin historical readiness passed');
