'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'agros-v615-'));process.env.AGROS_DATA_DIR=tmp;
const symbols={};for(const s of ['BTC','ETH','BNB','SOL','XRP','DOGE','ADA','LINK','LTC','AVAX','DOT','BCH','TRX','ATOM','ETC','NEAR','APT','SUI','ARB','OP','FIL','INJ','SEI','TON','UNI','AAVE','FET','PEPE','WIF','HBAR'])symbols[s+'USDT']={signals:1};
fs.writeFileSync(path.join(tmp,'st2-historical-training.json'),JSON.stringify({symbols,profiles:{}}));
const hist=[];for(let i=0;i<6;i++)hist.push({type:'HISTORICAL_SIGNAL',yon:'LONG',patternCode:'RRRR',context:{features:['BB=ALT','BBW=COK_GENIS','ATR=NORMAL','TREND20=UP','SESSION=ASYA','RENKO6=GRRRRR'],session:'ASYA',renko6:'GRRRRR'},candidates:{'0.50':{triggered:true,resolved:true,pnlPct:0.20},'1.00':{triggered:true,resolved:true,pnlPct:0.10}}});
fs.writeFileSync(path.join(tmp,'st2-historical-training-ledger.jsonl'),hist.map(JSON.stringify).join('\n')+'\n');
const a=require('./76_st2_adaptive_dna_entry.js');
const good={yon:'LONG',girisAnalizi:{patternKodu:'RRRR',renkoSonTuglaDizisi:'GRRRRR',renkoBb:{zone:'ALT',widthRegime:'COK_GENIS'},atrRegime:'NORMAL',trend20:'UP',session:'ASYA'}};
let g=a.gateDecision(good,0.75);assert.equal(g.executionMode,'PREMIER');assert.equal(g.allow,true);assert.equal(g.brick,0.50);
const unseen={yon:'SHORT',girisAnalizi:{patternKodu:'GGGG',renkoSonTuglaDizisi:'GGGGGG',renkoBb:{zone:'UST',widthRegime:'DAR'},atrRegime:'HIGH',trend20:'DOWN',session:'ABD'}};
g=a.gateDecision(unseen,0.75);assert.equal(g.executionMode,'SHADOW');assert.equal(g.allow,false);assert.equal(g.observe,true);
const c=a.contextFrom(good),key=a.dnaKey(c),st=a.blank();
const close=(id,a50,a100)=>({tradeId:id,candidates:{'0.50':{net:a50,triggered:true},'1.00':{net:a100,triggered:true}}});
st.dnaProfiles[key]={key,patternKey:a.patternKey(c),context:c,closes:[close('1',.01,.30),close('2',-.05,.20),close('3',.01,.20),close('4',.40,-.20)],changes:[]};a.save(st);
g=a.gateDecision(good,0.75);assert.equal(g.brick,1.00,'N4 must keep completed N1-3 block decision');assert.equal(g.reason,'LIVE_LAST3_WINNER');
st.dnaProfiles[key].closes.push(close('5',.40,-.20),close('6',.40,-.20));a.save(st);
g=a.gateDecision(good,0.75);assert.equal(g.brick,0.50,'N4-6 block must re-race and return historical leader');
const exit=require('./74_st2_renko_exit_evolution.js');const pos={yon:'LONG',sym:'X',sl:98,breakevenAktif:false,girisAnalizi:{patternKodu:'RRRR',renkoBoxSize:1}};exit.assign(pos);let u=exit.update(pos,102);assert.equal(u.active,false);pos.breakevenAktif=true;u=exit.update(pos,102);assert.equal(u.active,true);const first=pos.sl;u=exit.update(pos,101);assert.equal(pos.sl,first,'LONG Renko stop may never move backward');
console.log('✅ v6.1.5 Premier/Shadow + completed N3 cycles + safe-start Renko takeover passed');
