'use strict';
const assert=require('assert');const fs=require('fs');
const eco=fs.readFileSync('ecosystem.config.js','utf8');
const report=fs.readFileSync('2_rapor.js','utf8');
const pos=fs.readFileSync('4_pozisyon.js','utf8');
const entry=fs.readFileSync('73_st2_renko_entry_evolution.js','utf8');
const bot=fs.readFileSync('bot.js','utf8');
const rec=fs.readFileSync('78_st2_global_historical_reconciliation.js','utf8');
assert(eco.includes("max_memory_restart: '750M'"));
assert(!report.includes('${winningIntelligence.telegram()}'));
assert(report.includes('Replay Net'));
assert(report.includes('🧪 Entry Replay'));
assert(rec.includes('BAZ İŞLEM EKONOMİSİ'));assert(rec.includes('OPTİMİZE REPLAY'));
assert(entry.includes("skip='MANUAL_EXTERNAL_CLOSE'"));
assert(pos.includes('manuelDisKapanis'));
assert(pos.includes('!manuelDisKapanis && !leagueShadowOnly'));
assert(bot.includes('st2-startup-telegram.json'));assert(bot.includes('startupCooldownMs'));
console.log('✅ v6.1.6 final Telegram + manual close isolation + PM2 memory safety passed');
