'use strict';
const assert = require('assert');
const ops = require('./69_operation_intelligence_dashboard.js');
const version = require('./versiyon.js');
const metric = { opened: 6, active: 0, closed: 5, tp: 3, sl: 1, be: 1, net: 1.2, profitFactor: 2, expectancy: .24 };
const accounting = { opened: 10, closedScientific: 4, activeScientific: 3, activeGap: 2, closedGap: 1, difference: 0, reconciled: true, equation: '10 = 4 + 3 + 2 + 1' };
const prebuilt = { model: { aggregate: metric, trackMetrics: { reverse: metric }, league: { historicalPositiveCount: 40, reversePremierCount: 6, labLeagueCount: 719, nearProfitCount: 13 }, accounting }, premier: [], reverse: [], candidates: [], changes: { strengthening: 0, weakening: 0, exitChanges: 0, stopReady: 0, beReady: 0, reverseCandidates: 0 } };
const text = ops.telegram([], prebuilt);
assert(text.includes(`AGROS OPERASYON MERKEZİ — ${version.botSurumu}`), 'runtime version must be dynamic');
assert(text.includes('Premier gözlem defteri: Bilimsel aktif 3 | Premier GAP aktif 2'), 'scope labels missing');
assert(text.includes('Premier mutabakatı: 10 = 4 + 3 + 2 + 1 | Fark +0 ✅'), 'reconciliation line missing');
assert(!text.includes('📦 Aktif: Premier'), 'ambiguous legacy active label must be removed');
console.log('✅ v5.4.2 report scope/version consistency tests passed');
