'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'agros-v611-'));process.env.AGROS_DATA_DIR=tmp;process.env.AGROS_ST2_GLOBAL_HISTORICAL_AUTO_TRAIN='false';
const hist=[];for(const symbol of ['BTCUSDT','ETHUSDT','SOLUSDT'])for(let i=0;i<6;i++)hist.push({type:'HISTORICAL_SIGNAL',signalId:`${symbol}-${i}`,symbol,yon:'LONG',patternCode:'RRRR',candidates:{'1.00':{triggered:true,pnlPct:0.3,mfePct:0.5,maePct:-0.1}}});
fs.writeFileSync(path.join(tmp,'st2-historical-training-ledger.jsonl'),hist.map(JSON.stringify).join('\n')+'\n');
const live={schema:1,type:'SCIENTIFIC_CLOSE',tradeId:'t1',pos:{sym:'SOLUSDT',yon:'LONG',girisFiyati:100,girisAnalizi:{entryStrategy:'ST2_RENKO',patternKodu:'RRRR'}},result:{exitPrice:101,commission:0.08}};
fs.writeFileSync(path.join(tmp,'st2-renko-entry-evolution-ledger.jsonl'),JSON.stringify(live)+'\n');
fs.writeFileSync(path.join(tmp,'st2-renko-entry-evolution.json'),JSON.stringify({profiles:{},processedIds:{t1:true},bridge:{calls:1,accepted:1,skipped:{}},health:{stateRecords:1,ledgerRecords:1}}));
const runtime=require('./79_st2_global_historical_runtime.js');const rec=require('./78_st2_global_historical_reconciliation.js');const win=require('./75_st2_winning_intelligence.js');
const a=runtime.activate();assert.equal(a.activation,'READ_ONLY_ACTIVE');assert.equal(a.readyCoins,3);assert.equal(a.coins,30);assert.equal(rec.actualEconomy([live]).all.net,win.actualNet(live));assert.equal(rec.summary().reconciliation.ok,true);assert.equal(runtime.status().reconciliationOk,true);
console.log('✅ v6.1.1 global historical runtime & accounting reconciliation passed');
