'use strict';
const assert=require('assert');
const fs=require('fs'); const path=require('path'); const os=require('os');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'agros-v566-'));
process.env.AGROS_DATA_DIR=dir;
const entry=require('./73_st2_renko_entry_evolution.js');
const exit=require('./74_st2_renko_exit_evolution.js');
const s=entry.blank();
s.profiles['LONG|RRRR']={key:'LONG|RRRR',yon:'LONG',patternCode:'RRRR',closed:5,activeBrick:0.5,candidates:{'0.5':{samples:5,triggered:5,tp:4,sl:1,be:0,net:2,grossProfit:3,grossLoss:1,recent:[]}},history:[]};
entry.write(s);
assert.equal(entry.premierFor('LONG','RRRR').premier,true);
assert.equal(entry.premierFor('SHORT','GGGG').premier,false);
const pos={sym:'HOTUSDT',yon:'SHORT',girisAnalizi:{entryStrategy:'ST2_RENKO',patternKodu:'GGGG',renkoBoxSize:0.000001},sl:0.00034,breakevenAktif:false};
exit.assign(pos);
const report=exit.telegram([pos]);
assert.match(report,/Bilimsel kapanış: 0/);
assert.match(report,/Exit atanan: 1/);
assert.match(report,/Başlangıç fallback/);
const source=fs.readFileSync(path.join(__dirname,'72_st2_renko_entry.js'),'utf8');
assert.match(source,/YENİ ST2 RENKO PUSU/);
assert.doesNotMatch(source,/h\.telegramMesajGonder\(pusuKaniti\)/);
const motor=fs.readFileSync(path.join(__dirname,'motor.js'),'utf8');
assert.match(motor,/ST2 RENKO PREMIER BINDING/);
assert.match(motor,/leagueShadowOnly = false/);
console.log('✅ v5.6.6 Renko Premier binding + clean pusu Telegram + visible Exit Evolution passed');
