"use strict";
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const os=require('os');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'agros-v612-'));
process.env.AGROS_DATA_DIR=tmp;
process.env.AGROS_ST2_GLOBAL_HISTORICAL_AUTO_TRAIN='true';
const hafizaPath=require.resolve('./1_hafiza.js');
const h={state:{aktifPozisyonlar:[]}};
require.cache[hafizaPath]={id:hafizaPath,filename:hafizaPath,loaded:true,exports:h};
h.state.accountingContinuity={initializedAt:new Date().toISOString(),legacy:{activeAtMigration:0},current:{opened:60,closed:0,openedPremier:0,openedShadow:0,openedReal:0,closedPremier:0,closedShadow:0,closedReal:0},recentClosedIds:[]};
const accounting=require('./65_accounting_continuity.js');
const snap=accounting.snapshot([]);
assert.strictEqual(snap.reconciled,true,'canonical empty partitions must reconcile');
assert.strictEqual(snap.difference,0,'canonical difference must be zero');
assert.strictEqual(snap.rawLedgerDifference,60,'raw stale counter must remain audit-only');
const adaptive=require('./76_st2_adaptive_dna_entry.js');
assert.strictEqual(adaptive.contextComplete({rbb:'UNKNOWN',rbbw:'UNKNOWN',renko6:'UNKNOWN'}),false);
assert.strictEqual(adaptive.contextComplete({rbb:'ALT',rbbw:'DAR',renko6:'RRRRGG'}),true);
const runtime=require('./79_st2_global_historical_runtime.js');
assert.strictEqual(runtime.autoTrainEnabled(),true,'30-coin recovery must default enabled');
const certSource=fs.readFileSync(path.join(__dirname,'71_st1_final_certification.js'),'utf8');
assert(certSource.includes('ST2 FİNAL BİLİMSEL DENETİM'));
assert(!certSource.includes('ST1 FİNAL BİLİMSEL DENETİM — v5.4.1'));
console.log('✅ v6.1.2 global runtime consistency passed | canonical GAP + truthful DNA context + auto recovery + ST2 report');
